import type { SubsidyData } from "./data-zh";

// English translations of the 5 subsidy detail pages. Structure/slug/amounts/links/dates mirror data-zh.
export const subsidiesEn: SubsidyData[] = [
  {
    slug: "seiryoka",
    tag: "Labor-Saving",
    name: "Labor-Saving Subsidy (General Type)",
    nameJa: "中小企業省力化投資補助事業（一般型）(SME Labor-Saving Investment Subsidy, General Type)",
    amount: "Tiered by workforce size: 7.5M–80M JPY (101+ employees with the large wage-increase special exception: up to 100M JPY)",
    rate: "Subsidy rate 1/2 (small-scale / business-reconstruction operators 2/3); the portion above 15M JPY is subsidized at 1/3",
    deadline: "Public-offering round system (fixed application deadlines, not accepted on a rolling basis)",
    metaTitle: "Labor-Saving Subsidy (General Type) Explained | 7.5M–80M JPY by Workforce Size",
    metaDesc: "Application guide for the SME Labor-Saving Investment Subsidy (General Type). Five tiers by workforce size: 5 or fewer employees 7.5M, 6–20 employees 15M, 21–50 employees 30M, 51–100 employees 50M, 101+ employees 80M JPY (up to 100M JPY with the large wage-increase special exception). Subsidy rate 1/2 (small-scale 2/3). Public-offering round system. Introduce DX systems and automation equipment to cut costs and boost efficiency. One-on-one Chinese-language application support for Chinese-owned businesses in Japan.",
    heroDesc: "Cut costs and boost efficiency while reducing reliance on manual labor by introducing DX systems and automation equipment. The subsidy cap is tiered by workforce size: 5 or fewer employees 7.5M, 6–20 employees 15M, 21–50 employees 30M, 51–100 employees 50M, 101+ employees 80M JPY (with the large wage-increase special exception, 101+ employees can reach up to 100M JPY)",
    overview: [
      { label: "Subsidy cap (by workforce size)", value: "7.5M–80M JPY", sub: "5 or fewer 7.5M / 6–20 15M / 21–50 30M / 51–100 50M / 101+ 80M" },
      { label: "Subsidy rate", value: "1/2", sub: "Small-scale / business-reconstruction operators 2/3; portion above 15M JPY at 1/3" },
      { label: "Acceptance method", value: "Public-offering round system", sub: "Fixed application deadlines, not accepted on a rolling basis" },
    ],
    qualifications: [
      "SMEs or small-scale business operators (as defined by the Small and Medium-sized Enterprise Basic Act)",
      "Businesses in the process of introducing DX systems",
      "Businesses wishing to replace manual labor with IT or equipment",
      "Businesses facing labor shortages and seeking to improve operational efficiency",
      "Businesses wishing to reduce the cost of introducing systems",
      "Must formulate and submit a concrete plan for improving production efficiency",
    ],
    targets: [
      { item: "DX system introduction", detail: "ERP, CRM, office automation systems, business-process digitalization solutions, etc." },
      { item: "Production-line automation equipment", detail: "Robotic arms, automatic assembly machines, automatic inspection devices, etc." },
      { item: "Cleaning / transport robots", detail: "Commercial cleaning robots, AGV automated guided vehicles, etc." },
      { item: "POS and order-management systems", detail: "Smart cash registers and order-automation systems for restaurants / retail" },
      { item: "Automated warehouse / logistics systems", detail: "Automated storage/retrieval warehouses, automated sorting and conveyance systems" },
      { item: "AI image inspection / quality-control devices", detail: "Automatic product-appearance inspection, defective-item screening systems" },
    ],
    steps: [
      { step: "01", title: "Feasibility assessment for the subsidy", desc: "Conduct a comprehensive analysis of the company's business situation, development needs, and existing conditions to determine eligibility and probability of success." },
      { step: "02", title: "System and automation solution proposal", desc: "Tailor a system and automation solution to your industry characteristics and business processes, including software feature design, equipment selection, and process-optimization advice." },
      { step: "03", title: "Application document preparation and filing support", desc: "Assist in preparing the complete application package (application form, project plan, budget breakdown, corporate qualification documents, etc.) and guide you through the filing process." },
      { step: "04", title: "Grant decision and project implementation", desc: "Only after receiving the grant decision (kofu kettei) notice may you formally purchase equipment or begin system introduction. Do not place orders or make payments before that." },
      { step: "05", title: "Post-completion reporting and process support", desc: "After project completion, assist in preparing and submitting the performance report, ensuring compliance with subsidy-fund usage requirements and smooth receipt of the funds." },
    ],
    materials: [
      "Certificate of registered corporate matters (corporations) or final tax return (individuals)",
      "Financial statements for the most recent 2 fiscal years (balance sheet / profit and loss statement)",
      "Corporate tax return (including supplementary tables and account breakdowns)",
      "Labor-saving investment plan (prepared with our assistance)",
      "Quotation (equipment / system estimate)",
      "Employee roster and employment-insurance-related documents",
      "Wage-increase plan (prepared with our assistance)",
      "Confirmation letter from a certified support organization (if required)",
    ],
    faq: [
      {
        q: "My company has 5 or fewer employees. How much can we apply for?",
        a: "Businesses with 5 or fewer employees have a subsidy cap of 7.5M JPY (up to 10M JPY when the large wage-increase special exception is met). The subsidy rate is 1/2 (up to 2/3 for small-scale operators), with the company bearing the remainder. This is well suited to micro-businesses or sole proprietors looking to start digital transformation.",
      },
      {
        q: "How is the subsidy cap tiered by workforce size?",
        a: "The authority sets 5 tiers by number of regular employees: 5 or fewer 7.5M, 6–20 15M, 21–50 30M, 51–100 50M, 101+ 80M JPY. Only the specific combination of \"101+ employees AND meeting the large wage-increase special exception\" reaches a cap of 100M JPY — not every business can apply for 100M. We will determine which tier applies based on your actual headcount.",
      },
      {
        q: "What is the subsidy rate? Can the full amount be covered?",
        a: "The subsidy rate is 1/2 (SMEs), or 2/3 for small-scale operators / business-reconstruction operators. Note: the portion above 15M JPY is subsidized at a reduced rate of 1/3. The company must bear the remaining cost itself; there is no such thing as \"full subsidization\".",
      },
      {
        q: "Can this subsidy be applied for at any time?",
        a: "No. The General Type uses a \"public-offering round system\" with a clear opening and closing date for each round; missing it means waiting for the next round. Like competitively reviewed subsidies, it is a \"review-and-selection\" scheme: after submission the secretariat reviews the application, and approval is not guaranteed. We will help you seize the application window and improve your chances of selection.",
      },
      {
        q: "I have already purchased the equipment — can I still apply?",
        a: "No. You must receive the \"grant decision\" notice before purchasing equipment. If you buy first and apply later, the cost will not be recognized. This is a common mistake among business owners, so please be sure to consult us before applying.",
      },
      {
        q: "Can non-manufacturing sectors such as restaurants and services apply too?",
        a: "Yes. The Labor-Saving Subsidy is open to all industries: restaurants can apply for automatic dishwashers and delivery robots; service businesses can apply for AI reception systems, POS systems, etc. As long as it addresses labor shortages and improves efficiency, any industry is within scope.",
      },
    ],
    officialName: "中小企業省力化投資補助事業（一般型）事務局 (Secretariat, SME Labor-Saving Investment Subsidy, General Type)",
    officialUrl: "https://shoryokuka.smrj.go.jp/ippan",
    verifiedDate: "2026-08-01",
    note: "The amounts and subsidy rates on this page reflect the Reiwa 8 (FY2026) basis (unchanged from Reiwa 7). The Labor-Saving Subsidy is a review-and-selection, public-offering round scheme; submitting an application does not guarantee selection. Reiwa 8 (FY2026) Round 7 acceptance begins July 1, 2026; and from Round 7 onward, businesses with \"21 or more employees\" must additionally publish a general employer action plan (一般事業主行動計画の公表) as a mandatory requirement. Specific acceptance deadlines are governed by the official application MyPage and the latest public-offering guidelines.",
  },
  {
    slug: "ai-it",
    tag: "AI Adoption",
    name: "Digital / AI Adoption Subsidy",
    nameJa: "デジタル化・AI導入補助金2026（旧 IT導入補助金）(Digital / AI Adoption Subsidy 2026, formerly the IT Adoption Subsidy)",
    amount: "Normal frame up to 4.5M JPY (Invoice frame software up to 3.5M JPY)",
    rate: "Normal frame within 1/2 (within 2/3 when the minimum-wage requirement is met)",
    deadline: "Public-offering deadline rounds (joint application required via an IT Adoption Support Provider)",
    metaTitle: "Digital / AI Adoption Subsidy 2026 Explained | Normal Frame up to 4.5M JPY",
    metaDesc: "Application guide for the Digital / AI Adoption Subsidy 2026 (formerly the IT Adoption Subsidy). Normal frame 0.5M–4.5M JPY, subsidy rate within 1/2 (within 2/3 when the minimum-wage requirement is met). Requires a joint application with a registered \"IT Adoption Support Provider\" plus a registered IT tool, with clear public-offering deadlines. AI software procurement, system customization, and deployment training. One-on-one Chinese-language application support for Chinese-owned businesses in Japan.",
    heroDesc: "Japan's government funding dedicated to digital transformation (formerly the IT Adoption Subsidy): normal frame up to 4.5M JPY, subsidy rate within 1/2. Requires a joint application with a registered IT Adoption Support Provider and follows public-offering deadline rounds",
    overview: [
      { label: "Normal frame subsidy cap", value: "4.5M JPY", sub: "0.5M–4.5M JPY; Invoice frame software tier up to 3.5M" },
      { label: "Subsidy rate", value: "Within 1/2", sub: "Within 2/3 when the minimum-wage requirement is met" },
      { label: "Acceptance method", value: "Public-offering deadline system", sub: "Application via an IT Adoption Support Provider + a registered IT tool" },
    ],
    qualifications: [
      "Sole proprietors (including independent freelancers and individual businesses)",
      "SMEs / small-scale business operators (capital / employee-count caps vary by industry)",
      "Loss-making companies may also apply provided the IT introduction plan is feasible",
      "Must select an \"IT tool\" registered on the official list and apply jointly through an \"IT Adoption Support Provider\"",
      "Legally conducting business activities in Japan",
      "Must complete the grant application before the public-offering deadline (not accepted on a rolling basis)",
    ],
    targets: [
      { item: "Registered IT tools (software / cloud services)", detail: "Subsidized items must be \"IT tools\" registered on the official list — subscription or cloud-service fees for already-registered SaaS such as smart customer service, process optimization, and AI marketing" },
      { item: "Feature extensions / options of registered tools", detail: "Related feature extensions and module options within the scope of a registered tool, which must fall under that tool's registered category" },
      { item: "Related introduction services", detail: "Registered fees for introduction setup, initial consulting, and other related services provided by the IT Adoption Support Provider" },
      { item: "Invoice-frame-limited hardware", detail: "Permitted only under the Invoice (electronic transaction) frame, and limited to designated equipment such as PCs, tablets, print/scan devices, POS, and ticket machines; hardware such as GPU servers is not covered by the normal frame and must be confirmed item by item" },
    ],
    steps: [
      { step: "01", title: "Free eligibility diagnosis", desc: "A specialist consultant determines whether your AI adoption plan meets the eligibility criteria. Sole proprietors and loss-making companies can also be assessed; reply within 1 business day." },
      { step: "02", title: "Formulate the AI adoption plan", desc: "We help you identify business pain points, select AI tools, and produce a feasible AI adoption business plan." },
      { step: "03", title: "Prepare materials and submit the application", desc: "Our Gyoseishoshi team assists in completing all materials — application form, budget breakdown, benefit projections, etc. — and submits online to the competent authority." },
      { step: "04", title: "Implement after the grant decision", desc: "Only after receiving the grant decision notice may you formally purchase AI software/hardware or begin development. Do not pay in advance." },
      { step: "05", title: "Performance report and subsidy disbursement", desc: "After the AI system is introduced, submit the performance report; once approved, the subsidy is transferred to your account, arriving in roughly 2–3 months." },
    ],
    materials: [
      "Certificate of registered corporate matters (corporations) or business-opening notification (sole proprietors)",
      "Financial statements or final tax returns for the most recent 1–2 fiscal years",
      "AI adoption business plan (prepared with our assistance)",
      "Quotation for AI software / hardware / development services",
      "Benefit projection table (quantified sales increase / cost reduction / production-efficiency metrics)",
      "Data-security / compliance measures statement (if customer data is involved)",
      "Bank account certificate (for subsidy transfer)",
    ],
    faq: [
      {
        q: "Can sole proprietors and freelancers apply?",
        a: "Yes. Sole proprietors are within scope, as long as they legally operate in Japan, select an officially registered IT tool, and apply jointly through an IT Adoption Support Provider. Independent software developers and individual businesses are typical applicants.",
      },
      {
        q: "My company is currently operating at a loss — can we still apply?",
        a: "Yes. This subsidy does not use profitability as a threshold; even if you are currently in the red, you can apply as long as your IT/AI adoption plan is feasible with expected benefits. However, final selection is decided by the secretariat's review; applying does not mean automatic approval.",
      },
      {
        q: "Can this subsidy be applied for at any time? Are there SME-size requirements?",
        a: "It is not accepted on a rolling basis — this subsidy has clear public-offering deadline rounds, and the grant application must be completed before each round's deadline. Eligible parties are SMEs / small-scale operators and sole proprietors (with capital / employee-count caps by industry; large enterprises do not qualify). Furthermore, an \"IT Adoption Support Provider\" must first register the IT tool and apply jointly; individuals cannot submit alone.",
      },
      {
        q: "Can subscriptions such as ChatGPT Plus or Claude be applied for?",
        a: "General subscriptions themselves are not subsidized — this subsidy only covers \"IT tools\" registered on the official list. If the AI functionality you need is delivered through a registered tool or a customized solution provided by an IT Adoption Support Provider, the related cost may be included in the application. We will help match you with eligible registered tools.",
      },
      {
        q: "What happens if AI system development fails or falls short of expectations?",
        a: "This program focuses on the feasibility and actual implementation of the plan and does not make achieving results a condition for repaying the subsidy, but you must execute according to plan and submit a performance report. We will help you build a robust plan and provide guidance during implementation to avoid document flaws that could lead to later clawbacks.",
      },
    ],
    officialName: "デジタル化・AI導入補助金2026 事務局（中小機構）(Secretariat, Digital / AI Adoption Subsidy 2026; SMRJ)",
    officialUrl: "https://it-shien.smrj.go.jp/",
    verifiedDate: "2026-08-01",
    note: "This subsidy is a review-and-selection scheme (formerly the IT Adoption Subsidy), requiring a joint application through a registered IT Adoption Support Provider, with public-offering deadlines. The FY2026 frame structure and subsidy rates are unchanged from Reiwa 7; grant applications open March 30, 2026, and as of the verification date the latest available is the Normal frame 4th deadline of 17:00 on August 25, 2026 (monthly rounds thereafter). Amounts and deadlines are governed by the latest official public-offering guidelines; submitting an application does not guarantee selection.",
  },
  {
    slug: "career-up",
    tag: "Grant",
    name: "Career-Up (Regularization) Grant",
    nameJa: "キャリアアップ助成金（正社員化コース）(Career-Up Grant, Regularization Course)",
    amount: "SMEs: up to 800,000 JPY per person",
    rate: "Fixed-term → regular, priority-support target 800,000 JPY; fixed-term → regular, others 400,000 JPY; indefinite-term → regular 400,000 / 200,000 JPY",
    deadline: "Accepted year-round (paid in principle when requirements are met); apply starting 6 months after regularization",
    metaTitle: "Career-Up (Regularization) Grant Explained | SMEs up to 800,000 JPY per person",
    metaDesc: "Application guide for the Career-Up Grant (Regularization Course). The amount is determined by \"pre-regularization employment type + whether the person is a priority-support target\": fixed-term → regular, priority-support target 800,000/person; fixed-term → regular, others 400,000/person; indefinite-term → regular 400,000/200,000/person (all for SMEs, paid in 2 installments). Accepted year-round, paid in principle when requirements are met. One-on-one Chinese-language application support for Chinese-owned businesses in Japan.",
    heroDesc: "Retain excellent employees and lower staffing costs. When an SME converts a fixed-term priority-support-target employee to a regular employee, it can receive up to 800,000 JPY per person; the amount is determined by \"pre-regularization employment type + whether the person is a priority-support target\"",
    overview: [
      { label: "Fixed-term → regular, priority-support target", value: "800,000 JPY/person", sub: "SMEs, 400,000 × 2 installments" },
      { label: "Fixed-term → regular, others", value: "400,000 JPY/person", sub: "SMEs, 400,000 × 1 installment" },
      { label: "Indefinite-term → regular", value: "400,000 / 200,000 JPY/person", sub: "Priority-support target 400,000 / others 200,000" },
    ],
    qualifications: [
      "Must be an employment-insurance-covered establishment (already enrolled in employment insurance)",
      "Must formulate and submit a \"Career-Up Plan\" to the Labor Bureau in advance",
      "The converted employee must have been employed in a non-regular status for at least 6 months",
      "After conversion, the employee must be continuously employed as a regular employee for at least 6 months",
      "After conversion, the employee's wage must be raised by 3% or more",
      "The establishment must not have violated labor-related laws in the past 3 years",
    ],
    targets: [
      { item: "Regularization of fixed-term priority-support targets", detail: "Converting a fixed-term priority-support-target person to a regular employee: SMEs 800,000 JPY per person (400,000 × 2 installments)" },
      { item: "Regularization of other fixed-term employees", detail: "Converting other fixed-term employees to regular employees: SMEs 400,000 JPY per person (400,000 × 1 installment)" },
      { item: "Converting indefinite-term employees to regular", detail: "Converting indefinite-term employees (e.g., contract employees) to regular: SMEs priority-support target 400,000, others 200,000 JPY/person" },
      { item: "Converting dispatched workers to direct employment", detail: "Dispatched employee → directly employed regular employee (qualifies as a priority-support target, higher tier applies)" },
      { item: "Certification as a priority-support target", detail: "Fixed-term employees, dispatched workers, single parents, etc. employed for 3+ years who meet the priority-support-target definition qualify for the higher subsidy amount" },
    ],
    steps: [
      { step: "01", title: "Free consultation and eligibility confirmation", desc: "Confirm whether the establishment is enrolled in employment insurance and identify which employees meet the conversion criteria; usually reply within 1 business day." },
      { step: "02", title: "Formulate the Career-Up Plan in advance", desc: "Before implementing the conversion, the plan must be submitted to the competent Labor Bureau (at the latest 1 month before the implementation date); we help prepare all documents." },
      { step: "03", title: "Carry out the regular-employee conversion", desc: "Revise the employment contract, clarify indefinite-term employment terms, formally complete the conversion procedures, and raise the wage by 3% or more." },
      { step: "04", title: "Wait for the 6-month performance period", desc: "After conversion, continuously employ the person for 6 months, retaining wage-payment records, attendance records, and other supporting materials during this period." },
      { step: "05", title: "Submit the application and receive the grant", desc: "Within 2 months after the 6-month performance period ends, submit the application to the competent Labor Bureau; once approved, the grant is transferred to your account (about 3–6 months)." },
    ],
    materials: [
      "Career-Up Plan (must be submitted in advance)",
      "Employment-insurance insured-person-related documents",
      "Employment contracts (both before and after conversion)",
      "Work rules (including provisions for regular and non-regular employees)",
      "Wage-payment details for the 6 months after conversion",
      "Attendance ledger or time cards",
      "Production-efficiency improvement plan (if applying for the add-on)",
      "Certificate of registered corporate matters (in the case of a corporation)",
    ],
    faq: [
      {
        q: "Must the Career-Up Plan be submitted before conversion?",
        a: "Yes, this is a strict requirement. The Career-Up Plan must be submitted to the competent Labor Bureau on the day before the regular-employee conversion is implemented (at the latest before the implementation date). If you forget to submit it, you cannot apply for the grant, so please be sure to contact us in advance to handle it.",
      },
      {
        q: "Can I apply for multiple employees' conversions at once?",
        a: "Yes, each application can include multiple employees (the disbursement-application cap is 20 people per establishment per fiscal year). Each eligible employee can receive the subsidy separately, with the amount determined by each person's pre-regularization employment type and whether they are a priority-support target. Converting several employees at once can add up to a substantial total.",
      },
      {
        q: "When do the 400,000 and 800,000 amounts apply?",
        a: "The amount is jointly determined by two conditions — \"pre-regularization employment type\" and \"whether the person is a priority-support target\" — not by whether they are a new graduate: ① fixed-term → regular, SMEs 800,000/person for priority-support targets and 400,000/person for others; ② indefinite-term → regular, priority-support target 400,000 and others 200,000/person. A \"priority-support target\" refers to fixed-term employees, dispatched workers, single parents, etc. employed for 3+ years. In addition, newly graduated hires (new graduates employed within 1 year) are not eligible. We will determine which tier applies based on the employee's background.",
      },
      {
        q: "If I also arrange employee training, does the subsidy double?",
        a: "There is no \"automatic doubling\". The Regularization Course and the Human Resource Development Grant can be applied for in combination and each grant received separately; additionally, regularizing an employee after completing \"fixed-term practical training\" can raise the expense subsidy rate. This is not \"doubling\" but rather \"two systems each meeting their own requirements and each being paid.\" We will help you plan a sensible combination.",
      },
      {
        q: "Can I apply when converting a foreign employee in Japan to a regular employee?",
        a: "Yes. As long as the employee holds a legal work-eligible residence status (such as Engineer/Specialist in Humanities/International Services, Specified Skilled Worker, etc.) and is enrolled in employment insurance, they meet the application criteria. This is also a major advantage for Chinese-owned businesses in Japan.",
      },
      {
        q: "What is the 3% wage-increase requirement based on?",
        a: "It is compared against the hourly or monthly wage at the time of conversion, requiring at least a 3% increase after conversion. For example, an hourly wage of 1,000 JPY must reach at least 1,030 JPY after regularization. The Minimum Wage Act must also be observed. We will help you design a reasonable wage structure.",
      },
    ],
    officialName: "厚生労働省 キャリアアップ助成金（正社員化コース）(Ministry of Health, Labour and Welfare — Career-Up Grant, Regularization Course)",
    officialUrl: "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/part_haken/jigyounushi/career.html",
    verifiedDate: "2026-08-01",
    note: "The amounts on this page reflect the SME, Reiwa 8 (FY2026) basis (amounts unchanged from Reiwa 7). From Reiwa 8 (FY2026), the Career-Up Plan is simplified from prior certification to \"notification only\"; and a new \"information-disclosure add-on\" is established — publishing an overview and track record of the regularization system on your own website or the MHLW's \"Shokuba-lab\" adds 200,000 JPY per establishment (large enterprises 150,000 JPY; once only). This is a grant paid in principle when requirements are met (not a competitive-review scheme); it is governed by the latest MHLW guidance.",
  },
  {
    slug: "training",
    tag: "HR Development",
    name: "Employee Training Grant",
    nameJa: "人材開発支援助成金 (Human Resource Development Grant)",
    amount: "By course: HR Development 10M JPY / Investment in People 25M JPY / Business Expansion Reskilling 100M JPY (time-limited)",
    rate: "SME expense subsidy rate 45%–75% (add-ons when requirements are met) + wage subsidy of 800–1,000 JPY per person per hour",
    deadline: "Submit the training implementation plan notification 1–6 months before training starts (not a public-offering scheme)",
    metaTitle: "Employee Training Grant (Human Resource Development Grant) Explained | Tiered by Course",
    metaDesc: "Application guide for the Human Resource Development Grant. Annual per-establishment caps by course: HR Development Support 10M, Investment in People Promotion 25M, Business Expansion Reskilling Support 100M JPY (a time-limited measure through the end of Reiwa 8/FY2026). SME expense subsidy rate 45%–75% + wage subsidy of 800–1,000 JPY per person per hour. Courses such as hands-on AI must meet official training certification. One-on-one Chinese-language application support for Chinese-owned businesses in Japan.",
    heroDesc: "Focused on improving employee capabilities, with annual per-establishment caps tiered by course: HR Development Support 10M, Investment in People Promotion 25M, Business Expansion Reskilling Support up to 100M JPY (time-limited through the end of Reiwa 8/FY2026). Expense subsidy rate 45%–75% + wage subsidy",
    overview: [
      { label: "HR Development Support Course", value: "10M JPY", sub: "Per-establishment annual expense-subsidy cap" },
      { label: "Investment in People Promotion Course", value: "25M JPY", sub: "Per-establishment annual expense-subsidy cap" },
      { label: "Business Expansion Reskilling", value: "100M JPY", sub: "Time-limited measure (through the end of Reiwa 8/FY2026), not a universal cap" },
    ],
    qualifications: [
      "Must be an employment-insurance-covered establishment",
      "Must submit a \"Vocational Ability Development Promoter\" appointment notification to the competent Labor Bureau before training starts",
      "Must submit the \"training implementation plan notification\" 1 month before training starts",
      "Training must be outsourced to an external provider or use a certified off-JT format",
      "Training hours must meet the requirements (typically 10+ hours per course)",
      "Trainee employees must be employment-insurance insured persons",
    ],
    targets: [
      { item: "AI marketing and customer acquisition", detail: "Market analysis, customer-persona building, precise targeting of customer segments, and personalized marketing strategy formulation, improving acquisition capability and conversion rate" },
      { item: "AI operations automation", detail: "Automating business processes such as order processing, inventory management, and customer service, reducing manual work and lowering operating costs" },
      { item: "AI digital efficiency tools", detail: "How to use tools such as AI document processing, data analysis, and schedule management to comprehensively improve employee productivity" },
      { item: "AI market analysis and decision-making", detail: "Using AI for industry market analysis and market-trend forecasting to provide data support for corporate strategic decisions" },
      { item: "Other professional-skill training", detail: "Language training (Japanese / English), business management, professional-qualification courses, and more may also be included in the application" },
    ],
    steps: [
      { step: "01", title: "Free consultation and training-plan confirmation", desc: "Confirm whether the training content meets the grant requirements, choose the appropriate application framework, and focus on assessing the fit of hands-on AI courses." },
      { step: "02", title: "Appoint a \"Vocational Ability Development Promoter\"", desc: "Appoint an internal person in charge of vocational training at the establishment and submit the appointment notification to the Labor Bureau; we help prepare all documents." },
      { step: "03", title: "Submit the training implementation plan", desc: "One month before training starts, submit the training implementation plan to the Labor Bureau, specifying the training provider, content, duration, trainees, etc." },
      { step: "04", title: "Conduct the training and keep records", desc: "Complete the training as planned and retain all supporting materials — attendance records, completion certificates issued by the training provider, expense receipts, etc." },
      { step: "05", title: "Submit the disbursement application and receive the grant", desc: "Submit the disbursement application within 2 months after training ends; once approved, the grant is transferred to your account (about 3–5 months)." },
    ],
    materials: [
      "Training implementation plan (submitted 1 month before training starts)",
      "Vocational Ability Development Promoter appointment notification",
      "Employment-insurance insured-person-related documents",
      "Training provider's quotation / contract",
      "Trainee attendance records / attendance ledger",
      "Completion certificates issued by the training provider",
      "Expense receipts (training fees, facility fees, etc.)",
      "Wage-payment details (during the training period)",
    ],
    faq: [
      {
        q: "Can the business owner's own training be covered by the grant?",
        a: "No. The Employee Training Grant applies only to employment-insurance insured persons (employed staff); business owners are usually not enrolled in employment insurance and are therefore not eligible. However, employees (including foreign-national employees) can all apply.",
      },
      {
        q: "How much subsidy can hands-on AI courses receive?",
        a: "The subsidy consists of two parts: ① expense subsidy — SMEs receive 45%–75% of training fees by training type (add-ons possible when requirements such as wage increases / qualification allowances are met); ② wage subsidy — 800–1,000 JPY per person per hour of training (capped at 1,200 hours per person per training). If courses such as AI marketing and AI operations automation fall under \"advanced digital human-resource training / growth-field human-resource training,\" the expense subsidy rate can reach 75%, but must meet official training certification. Reaching the \"millions per person\" level is only possible under specific long-duration training plus add-ons and is not a general standard.",
      },
      {
        q: "Does the company have to advance the training fees first?",
        a: "Yes, the grant system works on an advance-then-reimburse basis. The company must pay the training fees first, submit the application after completing the training, and receive the grant back once approved. We recommend choosing a training program with a reasonable amount that your cash flow can accommodate.",
      },
      {
        q: "Can online courses (e-learning) be applied for?",
        a: "Yes. Online learning courses are also eligible, but must meet certain conditions: they must have completion-rate management functionality, record learning time, and be provided by an externally certified organization, etc. We can help confirm whether a specific course meets the requirements.",
      },
      {
        q: "What are the benefits of applying together with the Career-Up (Regularization) Grant?",
        a: "The two systems can be combined and each grant received separately — this is not \"doubling\" but each being paid after meeting its own requirements. In addition, adopting \"fixed-term practical training\" and regularizing the employee after training can raise the expense subsidy rate. We will help you plan a sensible combination of training and regularization to maximize the funding return within compliance.",
      },
    ],
    officialName: "厚生労働省 人材開発支援助成金 (Ministry of Health, Labour and Welfare — Human Resource Development Grant)",
    officialUrl: "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/koyou/kyufukin/d01-1.html",
    verifiedDate: "2026-08-01",
    note: "The \"100M JPY\" is only the per-establishment annual cap for the \"Business Expansion Reskilling Support Course\"; general AI/IT training goes through the HR Development Support Course (10M) or the Investment in People Promotion Course (25M). ⚠️ Important time limit: the Business Expansion Reskilling Support Course and the Investment in People Promotion Course are limited to the Reiwa 4–8 (FY2022–FY2026) period; Reiwa 8 (through March 31, 2027) is the final year and the authority has not yet announced an extension — if you intend to use them, be sure to submit the plan notification within this fiscal year. This is a grant paid in principle when requirements are met; amounts are governed by the latest MHLW guidance (verified against the Reiwa 8/FY2026 basis; amounts unchanged from Reiwa 7).",
  },
  {
    slug: "aircon",
    tag: "Energy-Saving Subsidy",
    name: "Energy-Efficient AC Retrofit Subsidy",
    nameJa: "ゼロエミッション化に向けた省エネ設備導入・運用改善支援事業（東京都）(Tokyo Metropolitan Support Project for Introducing Energy-Saving Equipment and Improving Operations toward Zero Emissions)",
    amount: "Tokyo Metropolitan: up to 45M JPY (subsidy rate 3/4)",
    rate: "Tokyo Metropolitan: subsidy rate up to 3/4 (3 tiers by CO2 reduction / diagnosis method)",
    deadline: "Round-based application (all applications go to a lottery when the budget is oversubscribed; not first-come, first-served)",
    metaTitle: "Energy-Efficient AC Retrofit Subsidy Explained | Tokyo Metropolitan up to 45M JPY, subsidy rate 3/4",
    metaDesc: "Application guide for the Tokyo Metropolitan energy-efficient AC retrofit subsidy (Zero-Emissions Energy-Saving Equipment Introduction Support Project). Three tiers by CO2 reduction / diagnosis method: annual reduction of 28t-CO2 or more, subsidy rate 3/4, cap 45M; prior energy-saving diagnosis + reduction of 3t or 30%, cap 25M (2/3); self-prepared plan, cap 10M (2/3). Round-based lottery; restaurants, schools, guesthouses, and businesses all eligible. One-on-one Chinese-language application support for Chinese-owned businesses in Japan.",
    heroDesc: "Tokyo Metropolitan subsidy for updating energy-saving equipment such as air conditioners at small- and medium-scale establishments (Cool Net Tokyo). Tiered by CO2 reduction and diagnosis method, with a subsidy rate up to 3/4 and up to 45M JPY; round-based application, with a lottery when the budget is oversubscribed",
    overview: [
      { label: "Top tier (reduction of 28t-CO2 or more)", value: "45M JPY", sub: "Subsidy rate 3/4" },
      { label: "Diagnosis + reduction of 3t or 30%", value: "25M JPY", sub: "Subsidy rate 2/3" },
      { label: "Self-prepared plan + reduction of 3t or 30%", value: "10M JPY", sub: "Subsidy rate 2/3" },
    ],
    qualifications: [
      "Have a business-use facility within Japan (shop, office, factory, school, guesthouse, etc.)",
      "Must replace existing old air conditioners with high-efficiency energy-saving equipment",
      "The new equipment must meet energy-saving standards (APF, etc.)",
      "Must present a clear energy-saving plan and projected energy-saving effect",
      "Must commission a professional contractor for installation and retain construction-related records",
      "Household air conditioners are not eligible",
    ],
    targets: [
      { item: "Restaurants", detail: "Updating air conditioning in kitchens and dining areas to improve the customer dining experience" },
      { item: "Schools / educational institutions", detail: "Updating air conditioning in classrooms and offices to create a comfortable learning environment for teachers and students" },
      { item: "Guesthouses / hotels", detail: "Updating guest-room air conditioning to improve guest satisfaction and brand reputation" },
      { item: "Office / retail businesses", detail: "Updating air conditioning in offices and shops to improve the employee and customer experience" },
      { item: "Factories / warehouses", detail: "Updating high-efficiency energy-saving air conditioning and ventilation systems in workshops and warehouses" },
    ],
    steps: [
      { step: "01", title: "Free eligibility diagnosis", desc: "Confirm the age of the existing air conditioners, the gap to energy-saving standards, the region, and the corresponding subsidy criteria, and give an initial assessment within 1 business day." },
      { step: "02", title: "Select equipment and obtain a quotation", desc: "Assist in selecting air-conditioner models that meet energy-saving standards and obtain a formal quotation from a designated contractor (including removal / installation fees)." },
      { step: "03", title: "Prepare and submit application materials", desc: "We assist in completing the online application, including the energy-saving plan, quotation, construction drawings, and all other materials." },
      { step: "04", title: "Carry out construction after the grant decision", desc: "Only after receiving the grant decision notice may you sign the construction contract and carry out the air-conditioner replacement work. Do not start construction in advance." },
      { step: "05", title: "Performance report and subsidy disbursement", desc: "After construction is complete, submit the completion report and receipts; once approved, the subsidy is transferred to your account (about 1–3 months)." },
    ],
    materials: [
      "Certificate of registered corporate matters (corporations) or final tax return (individuals)",
      "Most recent financial statements or final tax return",
      "Proof of model and installation year of the existing air conditioners (photos may be attached)",
      "Product specifications of the new equipment (including APF and energy-saving-standard attainment rate)",
      "Construction quotation (equipment cost / construction cost breakdown)",
      "Energy-saving plan (prepared with our assistance)",
      "Contractor registration certificate (if required)",
      "Construction-completion photos / receipts (after completion)",
    ],
    faq: [
      {
        q: "Can household air conditioners be applied for too?",
        a: "No. This program targets business-use facilities (shops, offices, factories, schools, guesthouses, etc.); household air conditioners are not eligible. If a residence is also used for business, it may qualify in some cases — we recommend consulting us for specifics.",
      },
      {
        q: "How much can the Tokyo Metropolitan subsidy cover?",
        a: "The Tokyo Metropolitan \"Zero-Emissions Energy-Saving Equipment Introduction Support Project\" has 3 tiers by CO2 reduction and whether a prior energy-saving diagnosis is done: ① annual reduction of 28t-CO2 or more, subsidy rate 3/4, cap 45M JPY; ② prior diagnosis + reduction of 3t or 30% or more, subsidy rate 2/3, cap 25M; ③ self-prepared plan + reduction of 3t or 30%, subsidy rate 2/3, cap 10M. The company must bear the portion outside the subsidy rate; there is no \"zero burden\". We will assess which tier applies and how much can be covered based on the on-site situation.",
      },
      {
        q: "Is this subsidy first-come, first-served?",
        a: "It is not first-come, first-served. Tokyo Metropolitan uses a \"round system\"; when a round's budget is oversubscribed, a lottery is held among all qualifying applications, so submitting an application does not guarantee winning. We will help you complete a compliant application within the acceptance period and improve the completeness of your materials.",
      },
      {
        q: "Are there similar subsidies outside Tokyo?",
        a: "Prefectures, municipalities, and the national level all have different energy-saving equipment update subsidy programs, with varying conditions, caps, and subsidy rates that must be verified separately for your region. Tell us your location and facility situation, and we will help match you with the current programs available locally.",
      },
      {
        q: "Can a tenant (lessee) of a leased shop apply?",
        a: "Generally yes, but written landlord consent is required. We recommend confirming the equipment-construction clauses in the lease contract before applying and preparing a landlord consent form. If the landlord wishes to be the applicant, the landlord may apply instead.",
      },
      {
        q: "Can construction be completed before applying?",
        a: "Absolutely not. As with all subsidies, construction may only be carried out after receiving the \"grant decision\" notice. Starting construction early means the cost will not be recognized and the subsidy application will be rejected, so please be careful.",
      },
    ],
    officialName: "クール・ネット東京（公益財団法人東京都環境公社）(Cool Net Tokyo / Tokyo Metropolitan Environmental Public Service Corporation)",
    officialUrl: "https://www.tokyo-co2down.jp/subsidy/zeroemi-shoene",
    verifiedDate: "2026-08-01",
    note: "This page reflects the Tokyo Metropolitan Reiwa 8 (FY2026) basis (the subsidy rates and the three-tier caps are unchanged from Reiwa 7). For Reiwa 8 (FY2026), acceptance increases from 5 to 6 rounds per year, the project period is extended through Reiwa 11 (FY2029), and the budget is about 10.2 billion JPY. Round-based lottery (when oversubscribed, all applications within the acceptance period go to a lottery, not first-come, first-served). As of the verification date, the 3rd acceptance period runs 7/31–8/14. Energy-saving subsidy programs outside Tokyo and at the national level vary and must be verified separately for your location. Amounts, subsidy rates, and acceptance periods are governed by the competent authority's latest announcements.",
  },
];
