import type { PillarSet } from "./types";
import { UI } from "./types";

const VERIFIED = "2026-09-03";
const SRC = {
  zeroemi: "https://www.tokyo-co2down.jp/subsidy/zeroemi-shoene",
  kosha: "https://www.tokyo-kosha.or.jp/support/josei/index.html",
  tokyocci: "https://www.tokyo-cci.or.jp/soudan/hojokin",
  seiryoka: "https://shoryokuka.smrj.go.jp/ippan/",
  itshien: "https://it-shien.smrj.go.jp/",
  career: "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/part_haken/jigyounushi/career.html",
  gbizinfo: "https://info.gbiz.go.jp/hojin/ichiran?hojinBango=5010401158340",
};
const NAP = {
  zh: ["地址", "〒102-0093 東京都千代田区平河町1-8-2 半蔵門パレス8階（半蔵門站步行 1 分钟·永田町站步行 5 分钟）"],
  en: ["Address", "Hanzomon Palace 8F, 1-8-2 Hirakawacho, Chiyoda-ku, Tokyo 102-0093 (1 min from Hanzomon Sta.)"],
  ja: ["所在地", "〒102-0093 東京都千代田区平河町1-8-2 半蔵門パレス8階（半蔵門駅徒歩1分・永田町駅徒歩5分）"],
};

export const areaTokyo: PillarSet = {
  zh: {
    path: "/area/tokyo",
    metaTitle: "东京补助金·助成金申请咨询｜千代田区事务所·中文对应·都独自制度一并覆盖",
    metaDesc: "面向东京 23 区及都下华人企业主的补助金·助成金申请支持：东京都ゼロエミ空调节能助成（最高 3/4）、東京都中小企業振興公社助成金、国家省力化·AI導入補助金、キャリアアップ助成金。千代田区半蔵門事务所可面谈，全程中文。",
    keywords: ["东京 补助金 申请", "东京 助成金 咨询", "东京 补助金 中文", "东京 个人事业主 补助金", "東京 補助金 中国語対応", "东京 空调 补助金", "东京 助成金 申请 公司"],
    heroEyebrow: "东京地区服务",
    heroTitle1: "在东京经营的华人企业，",
    heroTitle2: "补助金·助成金中文申请支持",
    heroDesc: "东京是华人企业最集中的地区，也是都独自助成制度最多的地区。国家制度 + 东京都制度一并规划，千代田区事务所可当面沟通。",
    summary: "株式会社志成コンサル总部位于東京都千代田区平河町1-8-2 半蔵門パレス8階（电话 03-6265-9756），为东京 23 区及多摩地区的在日华人企业主、个人事业主提供补助金·助成金申请支持，服务地域覆盖东京、神奈川、千叶、埼玉。东京事业所可同时利用国家制度（省力化投資補助金、デジタル化・AI導入補助金、キャリアアップ助成金等）与东京都独自制度（ゼロエミッション化 省エネ設備導入支援事業：助成率最高 3/4·上限 4,500 万円·回次抽签；東京都中小企業振興公社各类助成金：300 万〜2,000 万円）。全程中文，行政书士·社会保险劳务士·税理士·中小企业诊断士分工执行。",
    quickFacts: [
      { label: "事务所", value: "千代田区 半蔵門", sub: "半蔵門站 1 分钟；可预约面谈或线上" },
      { label: "东京独自·空调", value: "助成率最高 3/4", sub: "ゼロエミ 上限 4,500 万円；第 4 回 9/16〜10/2 受付" },
      { label: "东京独自·公社", value: "300 万〜2,000 万円", sub: "产品开发·贩路开拓·展会等，多数含个人事业主" },
      { label: "国家制度", value: "省力化 / AI導入 / 转正", sub: "全国通用，东京事业所同样适用" },
      { label: "服务地域", value: "东京·神奈川·千叶·埼玉", sub: "关东以外线上对应" },
    ],
    sections: [
      {
        id: "tokyo-only",
        h2: "东京都独自制度：只有都内事业所能用",
        blocks: [
          { type: "table", caption: "以东京都·公社官方页面为准（核验 2026-09-03）", head: ["制度", "对象", "上限 / 助成率", "受付", "华人企业典型用法"], rows: [
            ["ゼロエミッション化に向けた省エネ設備導入・運用改善支援事業（クール・ネット東京）", "都内中小企业·个人事业主的事业所", "年削减 28t-CO2 以上：3/4·4,500 万円 / 事前诊断+削减 3t 或 30%：2/3·2,500 万円 / 自作计划：2/3·1,000 万円", "令和 8 年度 第 4 回 9/16〜10/2；第 5 回 11/9〜11/20；第 6 回 2027/1/18〜1/29；预算超额抽签", "餐饮店·超市·民宿更换空调、冷冻冷藏、照明、给汤设备"],
            ["東京都中小企業振興公社 各类助成金", "都内中小企业·个人事业主·创业预定者", "按事业不同 300 万〜2,000 万円 / 1/2〜2/3", "各事业独立公募（如 市場開拓助成 300 万、地域資源活用 1,500 万等）", "新产品开发、展会出展、贩路开拓"],
            ["東京商工会議所 经营相談·补助金支援", "都内会员·非会员均可相談", "—（信息提供·申请支援·様式4 发行）", "常设", "持続化補助金的様式4 由所在地商工会議所发行"],
          ] },
          { type: "note", text: "东京都制度与国家制度可并行，但同一费用不可重复受领。ゼロエミ为抽签制且有自付部分，「零负担」「先着」说法均不准确。" },
          { type: "links", items: [{ label: "东京空调助成详解", href: "/subsidies/aircon" }, { label: "2026 公募日历", href: "/schedule" }] },
        ],
      },
      {
        id: "national",
        h2: "国家制度：东京事业所同样适用",
        blocks: [
          { type: "ul", items: [
            "中小企業省力化投資補助事業（一般型）：5 人以下 750 万〜101 人以上 8,000 万円，补助率 1/2（小規模 2/3）。第 8 回 8/18 公募开始。",
            "デジタル化・AI導入補助金2026：通常枠最高 450 万円，1/2 以内。第 5 次締切 10/7（予定）。",
            "キャリアアップ助成金（正社員化コース）：每人 20 万〜80 万円，通年。东京劳动局管辖。",
            "人材開発支援助成金：经费助成 45%〜75%；リスキリング支援コース 2026 年度为最终年度。",
          ] },
          { type: "links", items: [{ label: "省力化補助金", href: "/subsidies/seiryoka" }, { label: "AI導入補助金", href: "/subsidies/ai-it" }, { label: "转正助成金", href: "/subsidies/career-up" }, { label: "培训助成金", href: "/subsidies/training" }] },
        ],
      },
      {
        id: "areas",
        h2: "东京各区华人企业常见场景",
        blocks: [
          { type: "table", head: ["区域", "华人企业集中业态", "常见组合"], rows: [
            ["新宿·池袋·高田马场", "中餐、居酒屋、华人超市、留学服务", "ゼロエミ（空调）+ 省力化（自动点餐）+ キャリアアップ（兼职转正）"],
            ["上野·锦糸町·亀戸·西川口（埼玉）", "餐饮、食材批发、零售", "省力化（冷链·分拣）+ ゼロエミ（冷冻冷蔵）"],
            ["秋叶原·神田·千代田", "IT、贸易、跨境电商", "AI導入（ERP·系统）+ 人材開発支援（培训）"],
            ["银座·表参道·涩谷", "美容、美甲、按摩、高端餐饮", "AI導入（预约系统）+ 持続化（宣传）"],
            ["江东·江户川·葛西", "物流、仓储、贸易", "省力化（自动仓库·AGV）"],
            ["多摩·八王子·立川", "制造、加工、介护", "省力化 + 人材開発支援 + 都介护机器补助"],
          ] },
        ],
      },
      {
        id: "office",
        h2: "事务所与联系方式",
        blocks: [
          { type: "table", head: ["项目", "内容"], rows: [
            NAP.zh,
            ["电话", "03-6265-9756（工作日 9:00〜18:00）"],
            ["邮箱", "info@shisei-consult.jp"],
            ["法人番号", "5010401158340（GビズINFO 可查）"],
            ["对应语言", "中文·日语·英语"],
            ["面谈", "预约制；也可企业微信/线上会议"],
          ] },
          { type: "links", items: [{ label: "免费资格诊断（3 分钟）", href: "/contact" }, { label: "公司介绍与团队", href: "/about" }] },
        ],
      },
      {
        id: "flow",
        h2: "东京企业的申请流程（中文）",
        blocks: [
          { type: "ol", items: [
            "免费诊断：在留资格、业态、员工数、想做的事 → 1 个营业日内回复可用的国家+东京都制度。",
            "日程规划：对照公募日历倒推（ゼロエミ受付期、省力化締切、様式4 商工会議所截止）。",
            "材料制作：行政书士（补助金书类）、社会保险劳务士（雇用类助成金）、税理士（財務）、诊断士（事业计划）。",
            "提交·审查·抽签跟进：中文定期汇报。",
            "採択/交付决定后：实施合规、実績報告、入金确认。成功报酬制，比例签约前书面告知。",
          ] },
          { type: "note", text: "我们不承诺获批。补助金为竞争审查、东京ゼロエミ为抽签、助成金为要件审查，结果以主管机关为准。" },
        ],
      },
    ],
    faq: [
      { q: "我在东京开餐馆，换空调能拿多少补助？", a: "东京都ゼロエミ按 CO2 削减档：年削减 28t 以上 3/4·上限 4,500 万；事前省エネ诊断+削减 3t 或 30% 为 2/3·2,500 万；自作计划 2/3·1,000 万。需登记施工业者施工，回次抽签。第 4 回 9/16〜10/2 受付。" },
      { q: "东京都的助成和国家补助金能一起申请吗？", a: "可以并行，但同一费用不能重复受领。例如空调走ゼロエミ、自动点餐走省力化——设备不同即可。" },
      { q: "事务所在千代田区，我在八王子/町田，怎么服务？", a: "多摩地区同属东京都，都制度全部适用；沟通以线上、企业微信为主，必要时可预约面谈或上门。" },
      { q: "神奈川·千叶·埼玉的华人企业能委托吗？", a: "可以。国家制度全国适用；东京都独自制度限都内事业所，各县独自制度我们会逐一核实。" },
      { q: "东京个人事业主能用哪些？", a: "国家：持続化（50 万·2/3）、AI導入（450 万）、省力化（5 人以下 750 万）；东京都：ゼロエミ与公社多数助成明确含個人事業主。详见个人事业主专题。" },
      { q: "持続化補助金的様式4 在东京去哪办？", a: "向事业所所在地的商工会議所（東京商工会議所各支部）或商工会申请，第 20 回发行截止 12-04，需预约。" },
      { q: "可以先来事务所面谈再决定吗？", a: "可以，预约制。也可先做 3 分钟线上诊断，我们先判断能不能报再安排面谈，节省双方时间。" },
      { q: "东京都制度每年都有吗？", a: "ゼロエミ事业期已延至令和 11 年度、令和 8 年度预算约 102.3 亿円；公社助成每年度按事业公募。具体以当年度公告为准。" },
    ],
    sources: [
      { label: "東京都 ゼロエミッション化 省エネ設備導入・運用改善支援事業（クール・ネット東京）", url: SRC.zeroemi },
      { label: "東京都中小企業振興公社 助成金一覧", url: SRC.kosha },
      { label: "東京商工会議所 補助金・助成金 経営相談", url: SRC.tokyocci },
      { label: "中小企業省力化投資補助事業（一般型）", url: SRC.seiryoka },
      { label: "デジタル化・AI導入補助金2026", url: SRC.itshien },
      { label: "キャリアアップ助成金（厚生労働省）", url: SRC.career },
      { label: "株式会社志成コンサル 法人情報（GビズINFO）", url: SRC.gbizinfo },
    ],
    verifiedDate: VERIFIED,
    related: [
      { label: "东京空调节能助成详解", href: "/subsidies/aircon" },
      { label: "在日华人企业主专题", href: "/for/chinese-owners" },
      { label: "个人事业主专题", href: "/for/sole-proprietor" },
      { label: "2026 公募日历", href: "/schedule" },
      { label: "成功案例", href: "/cases" },
    ],
    ctaTitle1: "东京事业所能报什么？",
    ctaTitle2: "3 分钟中文免费诊断",
    ctaDesc: "国家 + 东京都制度一并判断，1 个营业日内回复。可预约半蔵門事务所面谈。不获批不收费。",
    breadcrumbParent: { label: "补助金种类", href: "/subsidies" },
    schemaType: "LocalBusiness",
    ui: UI.zh,
  },
  en: {
    path: "/area/tokyo",
    metaTitle: "Tokyo Subsidy & Grant Consulting | Chiyoda Office · Chinese-Language Support · Tokyo-Only Programs",
    metaDesc: "Subsidy and grant support for Chinese-owned businesses in Tokyo's 23 wards and Tama: Tokyo Zero-Emission AC grant (up to 3/4), Tokyo SME Support Center grants, national Labor-Saving and AI Adoption subsidies, Career-Up Grant. Office in Hanzomon, Chiyoda.",
    keywords: ["Tokyo subsidy consulting", "Tokyo grant Chinese business", "Tokyo AC subsidy", "subsidy consultant Chiyoda"],
    heroEyebrow: "Tokyo service area",
    heroTitle1: "Chinese-owned businesses in Tokyo:",
    heroTitle2: "subsidy & grant support in Chinese",
    heroDesc: "Tokyo has the largest concentration of Chinese-owned businesses and the most metropolitan-only grant programs. We plan national and Tokyo programs together, with in-person meetings in Chiyoda.",
    summary: "Shisei Consulting is headquartered at Hanzomon Palace 8F, 1-8-2 Hirakawacho, Chiyoda-ku, Tokyo (tel. 03-6265-9756) and supports Chinese business owners and sole proprietors across Tokyo, Kanagawa, Chiba and Saitama. Tokyo sites can use national programs (Labor-Saving, AI Adoption, Career-Up) together with Tokyo-only programs: the Zero-Emission energy-saving grant (up to 3/4, cap ¥45M, lottery rounds) and Tokyo SME Support Center grants (¥3M–¥20M). Full Chinese-language support by licensed professionals.",
    quickFacts: [
      { label: "Office", value: "Hanzomon, Chiyoda", sub: "1 min from Hanzomon Sta.; meetings by appointment or online" },
      { label: "Tokyo-only · AC", value: "Up to 3/4", sub: "Zero-Emission cap ¥45M; Round 4 9/16–10/2" },
      { label: "Tokyo-only · SME Center", value: "¥3M–¥20M", sub: "Product development, market expansion, exhibitions" },
      { label: "National", value: "Labor-Saving / AI / Career-Up", sub: "Apply equally to Tokyo sites" },
      { label: "Service area", value: "Tokyo · Kanagawa · Chiba · Saitama", sub: "Online elsewhere" },
    ],
    sections: [
      { id: "tokyo-only", h2: "Tokyo-only programs", blocks: [
        { type: "table", head: ["Program", "Eligible", "Cap / rate", "Intake", "Typical use"], rows: [
          ["Zero-Emission energy-saving grant (Cool Net Tokyo)", "SMEs and sole proprietors with Tokyo sites", "≥28t-CO2 cut: 3/4 · ¥45M / diagnosis + 3t or 30%: 2/3 · ¥25M / own plan: 2/3 · ¥10M", "FY2026 R4 9/16–10/2; R5 11/9–11/20; R6 2027/1/18–1/29; lottery", "AC, refrigeration, lighting, water heating"],
          ["Tokyo SME Support Center grants", "Tokyo SMEs, sole proprietors, founders", "¥3M–¥20M / 1/2–2/3", "Separate calls per program", "Product development, exhibitions"],
          ["Tokyo Chamber of Commerce", "Members and non-members", "Information, support, Form 4", "Ongoing", "Form 4 for Sustainability Subsidy"],
        ] },
        { type: "note", text: "Tokyo and national programs can run in parallel for different costs. Zero-Emission is a lottery with co-payment." },
        { type: "links", items: [{ label: "Tokyo AC grant", href: "/subsidies/aircon" }, { label: "2026 calendar", href: "/schedule" }] },
      ] },
      { id: "national", h2: "National programs for Tokyo sites", blocks: [
        { type: "ul", items: [
          "Labor-Saving Investment Subsidy: ¥7.5M–¥80M, 1/2 (2/3 small). Round 8 opened 8/18.",
          "Digitalization & AI Adoption 2026: up to ¥4.5M, up to 1/2. 5th deadline 10/7 (planned).",
          "Career-Up Grant: ¥200k–¥800k per person, year-round.",
          "HR Development Grant: 45–75% of costs; reskilling course ends FY2026.",
        ] },
        { type: "links", items: [{ label: "Labor-Saving", href: "/subsidies/seiryoka" }, { label: "AI Adoption", href: "/subsidies/ai-it" }, { label: "Career-Up", href: "/subsidies/career-up" }, { label: "HR Development", href: "/subsidies/training" }] },
      ] },
      { id: "areas", h2: "Typical scenarios by area", blocks: [
        { type: "table", head: ["Area", "Common businesses", "Typical combination"], rows: [
          ["Shinjuku · Ikebukuro · Takadanobaba", "Restaurants, supermarkets", "Zero-Emission + Labor-Saving + Career-Up"],
          ["Ueno · Kinshicho · Kameido", "F&B, wholesale, retail", "Labor-Saving + Zero-Emission"],
          ["Akihabara · Kanda · Chiyoda", "IT, trading, e-commerce", "AI Adoption + HR Development"],
          ["Ginza · Omotesando · Shibuya", "Beauty, premium dining", "AI Adoption + Sustainability"],
          ["Koto · Edogawa", "Logistics, warehousing", "Labor-Saving"],
          ["Tama · Hachioji · Tachikawa", "Manufacturing, care", "Labor-Saving + HR Development"],
        ] },
      ] },
      { id: "office", h2: "Office and contact", blocks: [
        { type: "table", head: ["Item", "Detail"], rows: [
          NAP.en,
          ["Tel", "03-6265-9756 (weekdays 9:00–18:00)"],
          ["Email", "info@shisei-consult.jp"],
          ["Corporate number", "5010401158340 (gBizINFO)"],
          ["Languages", "Chinese · Japanese · English"],
          ["Meetings", "By appointment; WeChat Work / online available"],
        ] },
        { type: "links", items: [{ label: "Free diagnosis", href: "/contact" }, { label: "About us", href: "/about" }] },
      ] },
      { id: "flow", h2: "Process for Tokyo businesses", blocks: [
        { type: "ol", items: [
          "Free diagnosis within one business day.",
          "Timeline against the calendar.",
          "Documents by licensed professionals.",
          "Submission, review and lottery follow-up.",
          "Post-adoption compliance, final report, disbursement. Success-fee disclosed before contract.",
        ] },
        { type: "note", text: "We do not guarantee approval." },
      ] },
    ],
    faq: [
      { q: "How much for replacing AC in my Tokyo restaurant?", a: "Zero-Emission: 3/4 up to ¥45M for ≥28t-CO2 cut; 2/3 up to ¥25M with diagnosis; 2/3 up to ¥10M with own plan. Registered contractor required; lottery. Round 4 9/16–10/2." },
      { q: "Can Tokyo and national programs be combined?", a: "Yes for different costs." },
      { q: "I am in Hachioji / Machida. Can you serve me?", a: "Yes — Tama is part of Tokyo; all Tokyo programs apply. Mostly online, in-person by appointment." },
      { q: "Kanagawa, Chiba, Saitama?", a: "Yes. National programs apply; Tokyo-only programs require Tokyo sites." },
      { q: "Sole proprietors in Tokyo?", a: "National Sustainability, AI Adoption, Labor-Saving; Tokyo Zero-Emission and most SME Center grants include sole proprietors." },
      { q: "Where to get Form 4 in Tokyo?", a: "Your local Tokyo Chamber of Commerce branch; deadline 12-04 for Round 20." },
      { q: "Can I visit before deciding?", a: "Yes, by appointment. A 3-minute online diagnosis first saves time." },
      { q: "Do Tokyo programs recur yearly?", a: "Zero-Emission runs to FY2029 (~¥10.23B FY2026); SME Center grants are called annually." },
    ],
    sources: [
      { label: "Tokyo Zero-Emission energy-saving grant", url: SRC.zeroemi },
      { label: "Tokyo SME Support Center grants", url: SRC.kosha },
      { label: "Tokyo Chamber of Commerce — subsidies", url: SRC.tokyocci },
      { label: "Labor-Saving Investment Subsidy", url: SRC.seiryoka },
      { label: "Digitalization & AI Adoption Subsidy 2026", url: SRC.itshien },
      { label: "Career-Up Grant", url: SRC.career },
      { label: "Shisei Consulting corporate record (gBizINFO)", url: SRC.gbizinfo },
    ],
    verifiedDate: VERIFIED,
    related: [
      { label: "Tokyo AC grant", href: "/subsidies/aircon" },
      { label: "Chinese business owners", href: "/for/chinese-owners" },
      { label: "Sole proprietors", href: "/for/sole-proprietor" },
      { label: "2026 calendar", href: "/schedule" },
      { label: "Case studies", href: "/cases" },
    ],
    ctaTitle1: "What can your Tokyo site apply for? ",
    ctaTitle2: "Free 3-minute diagnosis",
    ctaDesc: "National and Tokyo programs assessed together; reply within one business day. In-person meetings in Hanzomon by appointment.",
    breadcrumbParent: { label: "Subsidies", href: "/subsidies" },
    schemaType: "LocalBusiness",
    ui: UI.en,
  },
  ja: {
    path: "/area/tokyo",
    metaTitle: "東京の補助金・助成金申請サポート｜千代田区事務所・中国語対応・都独自制度も一括",
    metaDesc: "東京23区・多摩地域の在日華人経営者向け補助金・助成金申請サポート。東京都ゼロエミ空調省エネ助成（最大3/4）、東京都中小企業振興公社助成金、国の省力化・AI導入補助金、キャリアアップ助成金。千代田区半蔵門の事務所で面談可、全工程中国語対応。",
    keywords: ["東京 補助金 申請サポート", "東京 助成金 相談", "東京 補助金 中国語対応", "東京 個人事業主 補助金", "東京 空調 補助金", "千代田区 補助金 コンサル"],
    heroEyebrow: "東京エリア",
    heroTitle1: "東京で事業を営む華人企業の",
    heroTitle2: "補助金・助成金を中国語でサポート",
    heroDesc: "東京は華人企業が最も集中し、都独自の助成制度も最も多い地域。国の制度と都の制度を一括で計画し、千代田区の事務所で対面相談も可能です。",
    summary: "株式会社志成コンサルは東京都千代田区平河町1-8-2 半蔵門パレス8階（電話03-6265-9756）に本店を置き、東京23区および多摩地域の在日華人経営者・個人事業主に補助金・助成金の申請サポートを提供、対応地域は東京・神奈川・千葉・埼玉です。都内事業所は国の制度（省力化投資補助金、デジタル化・AI導入補助金、キャリアアップ助成金等）と東京都独自制度（ゼロエミッション化 省エネ設備導入支援事業：助成率最大3/4・上限4,500万円・回次抽選；東京都中小企業振興公社の各助成金：300万〜2,000万円）を併用できます。全工程中国語、行政書士・社会保険労務士・税理士・中小企業診断士の分担体制。",
    quickFacts: [
      { label: "事務所", value: "千代田区 半蔵門", sub: "半蔵門駅1分；予約制面談またはオンライン" },
      { label: "都独自・空調", value: "助成率最大3/4", sub: "ゼロエミ 上限4,500万円；第4回 9/16〜10/2" },
      { label: "都独自・公社", value: "300万〜2,000万円", sub: "製品開発・販路開拓・展示会；多くが個人事業主可" },
      { label: "国の制度", value: "省力化／AI導入／正社員化", sub: "全国共通、都内事業所も対象" },
      { label: "対応地域", value: "東京・神奈川・千葉・埼玉", sub: "その他はオンライン" },
    ],
    sections: [
      { id: "tokyo-only", h2: "東京都独自制度：都内事業所のみ", blocks: [
        { type: "table", head: ["制度", "対象", "上限／助成率", "受付", "典型的な活用"], rows: [
          ["ゼロエミッション化に向けた省エネ設備導入・運用改善支援事業（クール・ネット東京）", "都内中小企業・個人事業主の事業所", "年28t-CO2以上削減：3/4・4,500万円／診断＋3tまたは30%削減：2/3・2,500万円／自作計画：2/3・1,000万円", "令和8年度 第4回 9/16〜10/2；第5回 11/9〜11/20；第6回 2027/1/18〜1/29；予算超過時抽選", "飲食店・スーパー・民泊の空調・冷凍冷蔵・照明・給湯"],
          ["東京都中小企業振興公社 各助成金", "都内中小企業・個人事業主・創業予定者", "事業により300万〜2,000万円／1/2〜2/3", "事業ごとに公募", "製品開発・展示会・販路開拓"],
          ["東京商工会議所 経営相談・補助金支援", "会員・非会員", "情報提供・申請支援・様式4発行", "常設", "持続化補助金の様式4"],
        ] },
        { type: "note", text: "都制度と国の制度は併用可（同一経費は不可）。ゼロエミは抽選制かつ自己負担あり。" },
        { type: "links", items: [{ label: "東京 空調助成", href: "/subsidies/aircon" }, { label: "2026年 公募カレンダー", href: "/schedule" }] },
      ] },
      { id: "national", h2: "国の制度：都内事業所も対象", blocks: [
        { type: "ul", items: [
          "中小企業省力化投資補助事業（一般型）：750万〜8,000万円、1/2（小規模2/3）。第8回 8/18公募開始。",
          "デジタル化・AI導入補助金2026：最大450万円、1/2以内。第5次締切10/7（予定）。",
          "キャリアアップ助成金（正社員化コース）：1人20万〜80万円、通年。東京労働局管轄。",
          "人材開発支援助成金：経費助成45〜75%；リスキリングコースは令和8年度が最終年度。",
        ] },
        { type: "links", items: [{ label: "省力化補助金", href: "/subsidies/seiryoka" }, { label: "AI導入補助金", href: "/subsidies/ai-it" }, { label: "キャリアアップ助成金", href: "/subsidies/career-up" }, { label: "人材開発支援助成金", href: "/subsidies/training" }] },
      ] },
      { id: "areas", h2: "エリア別のよくある場面", blocks: [
        { type: "table", head: ["エリア", "華人企業の主な業態", "よくある組み合わせ"], rows: [
          ["新宿・池袋・高田馬場", "中華料理・居酒屋・華人スーパー", "ゼロエミ＋省力化＋キャリアアップ"],
          ["上野・錦糸町・亀戸", "飲食・食材卸・小売", "省力化＋ゼロエミ"],
          ["秋葉原・神田・千代田", "IT・貿易・越境EC", "AI導入＋人材開発支援"],
          ["銀座・表参道・渋谷", "美容・ネイル・高級飲食", "AI導入＋持続化"],
          ["江東・江戸川", "物流・倉庫", "省力化"],
          ["多摩・八王子・立川", "製造・介護", "省力化＋人材開発支援＋都介護補助"],
        ] },
      ] },
      { id: "office", h2: "事務所・連絡先", blocks: [
        { type: "table", head: ["項目", "内容"], rows: [
          NAP.ja,
          ["電話", "03-6265-9756（平日9:00〜18:00）"],
          ["メール", "info@shisei-consult.jp"],
          ["法人番号", "5010401158340（GビズINFO）"],
          ["対応言語", "中国語・日本語・英語"],
          ["面談", "予約制；企業WeChat・オンライン可"],
        ] },
        { type: "links", items: [{ label: "無料診断（3分）", href: "/contact" }, { label: "会社案内", href: "/about" }] },
      ] },
      { id: "flow", h2: "東京の事業者の申請フロー", blocks: [
        { type: "ol", items: [
          "無料診断：1営業日以内に国＋都の対象制度をご回答。",
          "スケジュール：公募カレンダーから逆算。",
          "書類作成：行政書士・社労士・税理士・診断士の分担。",
          "提出・審査・抽選のフォロー。",
          "採択後：実施・実績報告・入金確認。成功報酬制。",
        ] },
        { type: "note", text: "採択を保証するものではありません。" },
      ] },
    ],
    faq: [
      { q: "東京の飲食店で空調を更新すると助成はいくら？", a: "ゼロエミはCO2削減区分により、年28t以上削減で3/4・上限4,500万、診断＋3tまたは30%削減で2/3・2,500万、自作計画で2/3・1,000万。登録施工業者による施工、抽選制。第4回は9/16〜10/2。" },
      { q: "都の助成と国の補助金は併用できますか？", a: "経費が異なれば併用可。同一経費の重複受給は不可。" },
      { q: "八王子・町田ですが対応できますか？", a: "多摩地域も東京都のため都制度はすべて対象。オンライン中心、必要に応じ面談・訪問。" },
      { q: "神奈川・千葉・埼玉でも依頼できますか？", a: "可能。国の制度は全国対象、都独自制度は都内事業所限定。各県制度は個別に確認。" },
      { q: "東京の個人事業主は何が使えますか？", a: "国：持続化・AI導入・省力化；都：ゼロエミと公社助成の多くが個人事業主を含みます。" },
      { q: "持続化補助金の様式4はどこで？", a: "事業所所在地の商工会議所（東京商工会議所各支部）または商工会。第20回は12-04まで。" },
      { q: "事務所で面談してから決めたい", a: "予約制で対応。先に3分のオンライン診断で申請可否を確認すると効率的です。" },
      { q: "都の制度は毎年ありますか？", a: "ゼロエミは令和11年度まで、令和8年度予算約102.3億円。公社助成は年度ごとに公募。" },
    ],
    sources: [
      { label: "東京都 ゼロエミッション化 省エネ設備導入・運用改善支援事業", url: SRC.zeroemi },
      { label: "東京都中小企業振興公社 助成金一覧", url: SRC.kosha },
      { label: "東京商工会議所 補助金・助成金", url: SRC.tokyocci },
      { label: "中小企業省力化投資補助事業（一般型）", url: SRC.seiryoka },
      { label: "デジタル化・AI導入補助金2026", url: SRC.itshien },
      { label: "キャリアアップ助成金", url: SRC.career },
      { label: "株式会社志成コンサル 法人情報（GビズINFO）", url: SRC.gbizinfo },
    ],
    verifiedDate: VERIFIED,
    related: [
      { label: "東京 空調省エネ助成", href: "/subsidies/aircon" },
      { label: "在日華人経営者向け", href: "/for/chinese-owners" },
      { label: "個人事業主向け", href: "/for/sole-proprietor" },
      { label: "2026年 公募カレンダー", href: "/schedule" },
      { label: "導入事例", href: "/cases" },
    ],
    ctaTitle1: "都内事業所で使える制度は？ ",
    ctaTitle2: "3分で無料診断",
    ctaDesc: "国＋都の制度を一括判定、1営業日以内にご回答。半蔵門事務所での面談も予約可。不採択なら費用はいただきません。",
    breadcrumbParent: { label: "補助金の種類", href: "/subsidies" },
    schemaType: "LocalBusiness",
    ui: UI.ja,
  },
};
