import type { PillarSet } from "./types";
import { UI } from "./types";

const VERIFIED = "2026-09-03";
const SRC = {
  seiryoka: "https://shoryokuka.smrj.go.jp/ippan/",
  itshien: "https://it-shien.smrj.go.jp/",
  career: "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/part_haken/jigyounushi/career.html",
  jinzai: "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/koyou/kyufukin/d01-1.html",
  zeroemi: "https://www.tokyo-co2down.jp/subsidy/zeroemi-shoene",
  gbizinfo: "https://info.gbiz.go.jp/hojin/ichiran?hojinBango=5010401158340",
  chusho: "https://www.chusho.meti.go.jp/",
};
const REL = {
  zh: [
    { label: "个人事业主可申请的补助金", href: "/for/sole-proprietor" },
    { label: "补助金 vs 助成金 vs 融资", href: "/compare" },
    { label: "2026 公募日历", href: "/schedule" },
    { label: "东京地区服务", href: "/area/tokyo" },
    { label: "成功案例", href: "/cases" },
  ],
  en: [
    { label: "Subsidies for sole proprietors", href: "/for/sole-proprietor" },
    { label: "Subsidy vs. grant vs. loan", href: "/compare" },
    { label: "2026 calendar", href: "/schedule" },
    { label: "Tokyo service area", href: "/area/tokyo" },
    { label: "Case studies", href: "/cases" },
  ],
  ja: [
    { label: "個人事業主向け補助金", href: "/for/sole-proprietor" },
    { label: "補助金・助成金・融資の違い", href: "/compare" },
    { label: "2026年 公募カレンダー", href: "/schedule" },
    { label: "東京エリアのサポート", href: "/area/tokyo" },
    { label: "導入事例", href: "/cases" },
  ],
};

export const chineseOwners: PillarSet = {
  zh: {
    path: "/for/chinese-owners",
    metaTitle: "在日华人企业主补助金申请指南｜签证·税务·劳务一并考虑的中文支持方案",
    metaDesc: "在日华人经营的餐饮、贸易、美业、零售、IT 企业如何申请日本补助金·助成金：最常用的 5 类制度、与经营管理签证的关系、华人企业 6 个常见误区、行业入口与中文服务分工。行政书士·社劳士·税理士·中小企业诊断士联合团队。",
    keywords: ["在日华人 补助金", "在日华人 企业 补助金 申请", "华人 助成金 日本", "在日中国人 補助金", "华人企业 补助金 中文", "日本 补助金 中文 咨询"],
    heroEyebrow: "在日华人企业主专题",
    heroTitle1: "在日华人企业的补助金申请，",
    heroTitle2: "为什么需要「懂制度也懂你」的团队",
    heroDesc: "华人企业申请日本补助金，卡点往往不在制度本身，而在语言、材料习惯、签证与税务联动。本页把这些问题一次讲清。",
    summary: "在日华人企业主（法人或個人事業主）可申请的日本补助金·助成金与日本企业完全相同，无国籍限制；只要在日本有登记的事业实体、按期纳税申告、在留资格允许经营即可。最常用的五类制度是：中小企業省力化投資補助金一般型（750 万〜8,000 万円、补助率 1/2）、デジタル化・AI導入補助金2026（最高 450 万円、1/2 以内）、キャリアアップ助成金正社員化（每人最高 80 万円）、人材開発支援助成金（经费助成 45%〜75%）、东京都ゼロエミ空调节能助成（助成率最高 3/4、上限 4,500 万円）。志成コンサル（法人番号 5010401158340，东京千代田区）以中文提供从诊断到入金的申请支持，由行政书士·社会保险劳务士·税理士·中小企业诊断士分工执行。",
    quickFacts: [
      { label: "国籍限制", value: "没有", sub: "看事业实体、纳税记录、在留资格是否允许经营" },
      { label: "买设备·省人", value: "省力化 最高 8,000 万円", sub: "按员工数分 5 档；5 人以下 750 万；补助率 1/2（小規模 2/3）" },
      { label: "上系统·AI", value: "AI導入 最高 450 万円", sub: "补助率 1/2 以内；须经 IT 導入支援事業者" },
      { label: "转正·培训", value: "80 万円/人 · 45〜75%", sub: "キャリアアップ / 人材開発支援（厚劳省系，要件支给）" },
      { label: "东京换空调", value: "助成率最高 3/4", sub: "ゼロエミ 上限 4,500 万円；回次抽签，非先着" },
    ],
    sections: [
      {
        id: "top5",
        h2: "华人企业最常申请的 5 类制度",
        blocks: [
          { type: "table", caption: "上限·补助率为官方 2026 现行值（核验 2026-09-03）", head: ["场景", "制度（日文正式名）", "上限 / 补助率", "性质", "华人企业典型用法"], rows: [
            ["买设备、减人手", "中小企業省力化投資補助事業（一般型）", "5 人以下 750 万〜101 人以上 8,000 万円 / 1/2（小規模 2/3）", "経産省·公募回制·竞争採択", "餐饮自动点餐·洗碗机，物流分拣，工厂自动化"],
            ["上软件、AI、系统", "デジタル化・AI導入補助金2026", "通常枠 5 万〜450 万円 / 1/2 以内", "経産省·按月締切·须 IT 支援事業者", "会计/预约/POS/ERP、跨境电商后台、AI 客服"],
            ["兼职转正", "キャリアアップ助成金（正社員化コース）", "每人 20 万〜80 万円", "厚労省·通年·要件支给", "餐饮/零售兼职转正，留学生毕业留用（需先转在留资格）"],
            ["员工培训", "人材開発支援助成金", "经费助成 45%〜75% + 赁金助成 800〜1,000 円/小时", "厚労省·计划届制", "日语/技能/DX 培训；リスキリング支援コース为 2026 年度最终年度"],
            ["东京店铺换空调、照明", "ゼロエミッション化 省エネ設備導入・運用改善支援事業", "助成率 3/4·上限 4,500 万円（按 CO2 削减档）", "东京都·回次抽签", "餐饮店、超市、民宿冷暖设备更新"],
          ] },
          { type: "links", items: [{ label: "省力化補助金详解", href: "/subsidies/seiryoka" }, { label: "AI導入補助金详解", href: "/subsidies/ai-it" }, { label: "转正助成金详解", href: "/subsidies/career-up" }, { label: "培训助成金详解", href: "/subsidies/training" }, { label: "东京空调助成详解", href: "/subsidies/aircon" }] },
        ],
      },
      {
        id: "visa",
        h2: "与经营管理签证、永住的关系",
        blocks: [
          { type: "p", text: "补助金审查不看国籍，看的是「在日本合法经营的事业者」。以下是华人企业主最常问的三点（仅为一般性说明，不构成法律意见，具体请咨询行政书士）：" },
          { type: "ul", items: [
            "经营管理签证持有者作为法人代表申请补助金：可以。补助金不会影响签证审查；反过来，按期申告、社保加入、合规雇用等补助金要件，与签证更新看重的「事业稳定性·合规性」高度重合。",
            "永住者·日本人配偶者·定住者：经营活动无限制，与日本人同等。",
            "留学·家族滞在等身份：原则上不能作为经营者申请。想以员工身份被雇用并转正，需先变更为可就劳的在留资格。",
          ] },
          { type: "note", text: "补助金入金属于事业收入（雑収入），影响当期利润与税额；与税理士提前规划入账年度，避免签证更新时财务报表出现意料之外的波动。" },
        ],
      },
      {
        id: "mistakes",
        h2: "华人企业申请补助金的 6 个常见误区",
        blocks: [
          { type: "ol", items: [
            "先买再报：省力化、AI導入、持続化都只补交付決定后的支出。国内「先干后补」的习惯在日本会直接导致不採択或返还。",
            "把「補助金」当成「助成金」：前者是竞争审查、会不採択；后者要件满足原则支给。听到「一定能拿」的就是把两者混了，或在夸大。",
            "相信「零负担」「最快 N 个月到账」：东京空调助成是抽签制且有自付部分；补助金是后付制，需自筹周转资金。",
            "找无资格中介：补助金书类作成代行属行政書士业务，助成金申请代理属社会保険労務士专属业务。无资格者收费代办有法律风险，出问题客户自己承担。",
            "材料按国内习惯准备：日本审查看的是「事业计划的逻辑」与「数字的可验证性」，不是关系、不是规模宣传。決算書、申告書、雇用契約、就業規則要齐、要一致。",
            "拿到採択就松懈：採択→交付決定→实施→实绩报告→审核→入金，实绩报告不合规会被减额甚至取消。",
          ] },
        ],
      },
      {
        id: "industry",
        h2: "按行业看：你这个行业最常用什么",
        blocks: [
          { type: "table", head: ["行业", "常见投入", "优先制度", "备注"], rows: [
            ["中餐·居酒屋·拉面", "自动点餐、洗碗机、换空调", "省力化（一般型或カタログ型）、东京ゼロエミ、キャリアアップ", "东京店铺空调助成率最高 3/4，抽签制"],
            ["华人超市·零售", "POS、冷柜、自动结账", "省力化、AI導入、ゼロエミ", "冷柜属节能设备可评估 ゼロエミ"],
            ["美容·美甲·按摩", "预约系统、设备、兼职转正", "AI導入、持続化、キャリアアップ", "个人事业主居多，见个人事业主专题"],
            ["贸易·跨境电商", "ERP、仓储自动化、跨境系统", "AI導入、省力化", "系统须在 IT 工具名录内"],
            ["IT·软件", "研发人才培训、内部系统", "人材開発支援、AI導入", "リスキリング支援コース 2026 年度为最终年度"],
            ["介护·医疗·福祉", "介护机器人、ICT、人员培训", "省力化、人材開発支援、东京都介护机器补助", "另有厚劳省·都独自介护 ICT 补助"],
            ["民宿·酒店", "自助入住、空调、清扫机器人", "省力化、ゼロエミ", "民宿需有合法营业许可"],
          ] },
          { type: "links", items: [{ label: "个人事业主专题", href: "/for/sole-proprietor" }] },
        ],
      },
      {
        id: "how",
        h2: "中文服务流程与持牌人分工",
        blocks: [
          { type: "ol", items: [
            "免费诊断（中文，1 个营业日内回复）：确认在留资格、事业形态、员工数、想做的事 → 给出能报/不能报/先补什么。",
            "方案与时间表：对照公募日历倒推，明确 GビズID、見積、事业计划的截止节点。",
            "材料制作：补助金申请书类由行政书士制作；雇用类助成金手续由社会保险劳务士办理；财务数据由税理士核对；事业计划由中小企业诊断士把逻辑。",
            "提交与审查跟进：补充质询由我们对接事务局，进度定期中文汇报。",
            "採択后：交付决定、实施期间的合规提醒、实绩报告、入金确认。费用为成功报酬制，具体比例在签约前书面告知。",
          ] },
          { type: "note", text: "我们不承诺获批。补助金是竞争审查，助成金是要件审查，结果以主管机关为准。我们能做的是把「能报的报对、该补的先补、材料一次做齐」。" },
          { type: "links", items: [{ label: "服务流程与费用", href: "/service" }, { label: "成功案例（含口径说明）", href: "/cases" }, { label: "免费诊断", href: "/contact" }] },
        ],
      },
    ],
    faq: [
      { q: "外国人经营的公司申请补助金会被歧视或降分吗？", a: "不会。审查基于事业计划、财务与要件，国籍不是评分项。实际影响审查的是材料完整度与计划逻辑——这恰恰是语言不通时最容易失分的地方。" },
      { q: "公司刚成立、还没有第一期決算，能申请吗？", a: "省力化与 AI導入没有硬性年限要求，但审查看财务基础；新设法人通常建议先用持続化補助金（创业型特例）或等第一期決算后再报大额制度。具体按当回公募要領。" },
      { q: "员工都是华人兼职、有的还是留学生，能申请キャリアアップ助成金吗？", a: "对象是「雇用保险被保险者」且转正后在留资格允许全职就劳。留学生需先变更为技術・人文知識・国際業務等就劳资格；资格外活动（周 28 小时）身份不能转正。" },
      { q: "申请补助金会不会让税务署、入管更关注我？", a: "补助金申请会核对申告与社保记录，本身就是合规经营的体现。若存在滞纳或未加入社保，应先整改再申请——这类问题不解决，补助金也过不了。" },
      { q: "可以用中文提交申请材料吗？", a: "不可以，所有申请材料必须是日文。我们的价值正在于：你用中文沟通、提供原始资料，日文书类由持牌专业人员制作并对齐制度用语。" },
      { q: "补助金到账后要交税吗？", a: "要。补助金计入事业收入（法人为雑収入），当期课税。购置固定资产时可利用「圧縮記帳」递延，需由税理士规划。" },
      { q: "你们和普通中介有什么区别？", a: "三点：①持牌人分工执行（行政书士/社劳士/税理士/诊断士），补助金与助成金两条线都能合规做；②数据口径公开，金额均标官方来源与核验日期；③不承诺获批，先免费判断值不值得报。" },
      { q: "大阪、名古屋、福冈的华人企业也能委托吗？", a: "可以。多数制度是全国性的，线上即可完成；东京都独自助成（如ゼロエミ）仅限都内事业所。地方独自制度我们会逐一核实后再建议。" },
    ],
    sources: [
      { label: "中小企業省力化投資補助事業（一般型）", url: SRC.seiryoka },
      { label: "デジタル化・AI導入補助金2026", url: SRC.itshien },
      { label: "キャリアアップ助成金（厚生労働省）", url: SRC.career },
      { label: "人材開発支援助成金（厚生労働省）", url: SRC.jinzai },
      { label: "東京都 ゼロエミッション化 省エネ設備導入支援事業（クール・ネット東京）", url: SRC.zeroemi },
      { label: "株式会社志成コンサル 法人情報（GビズINFO）", url: SRC.gbizinfo },
    ],
    verifiedDate: VERIFIED,
    related: REL.zh,
    ctaTitle1: "你的企业能报哪一个？",
    ctaTitle2: "免费中文诊断",
    ctaDesc: "在留资格、行业、员工数、想做的事——4 个问题，工作日 1 个营业日内给出能报的制度与准备清单。不获批不收费。",
    breadcrumbParent: { label: "补助金种类", href: "/subsidies" },
    ui: UI.zh,
  },
  en: {
    path: "/for/chinese-owners",
    metaTitle: "Japanese Subsidies for Chinese Business Owners in Japan | Visa, Tax & Labor Considered",
    metaDesc: "How Chinese-owned restaurants, trading firms, salons, retailers and IT companies in Japan apply for subsidies and grants: the 5 most-used programs, visa relationship, 6 common mistakes, and a licensed bilingual team.",
    keywords: ["Chinese business owner Japan subsidy", "foreign owned company Japan hojokin", "subsidy consulting Chinese language Japan"],
    heroEyebrow: "For Chinese business owners",
    heroTitle1: "Subsidies for Chinese-owned businesses in Japan:",
    heroTitle2: "why you need a team that knows both the system and you",
    heroDesc: "The blockers are rarely the programs themselves — they are language, document habits, and how subsidies interact with visas and tax. This page covers all of it.",
    summary: "Chinese business owners in Japan (companies or sole proprietors) are eligible for exactly the same subsidies as Japanese businesses — there is no nationality restriction. Requirements: a registered business, tax filings, and a residence status permitting business activity. The five most-used programs: Labor-Saving Investment Subsidy (¥7.5M–¥80M, 1/2), Digitalization & AI Adoption Subsidy 2026 (up to ¥4.5M, up to 1/2), Career-Up Grant (up to ¥800k per person), Human Resource Development Grant (45–75% of costs), and Tokyo Zero-Emission energy-saving grant (up to 3/4, cap ¥45M). Shisei Consulting (corporate number 5010401158340, Chiyoda, Tokyo) supports the full process in Chinese with licensed Gyoseishoshi, Sharoshi, Zeirishi and SME consultants.",
    quickFacts: [
      { label: "Nationality limit", value: "None", sub: "Business entity, tax record, and residence status matter" },
      { label: "Equipment", value: "Labor-Saving up to ¥80M", sub: "5 tiers by headcount; ¥7.5M for ≤5; 1/2 (2/3 small)" },
      { label: "Software / AI", value: "AI Adoption up to ¥4.5M", sub: "Up to 1/2; via registered IT vendor" },
      { label: "Staff", value: "¥800k/person · 45–75%", sub: "Career-Up / HR Development grants (MHLW)" },
      { label: "Tokyo AC", value: "Up to 3/4", sub: "Zero-Emission grant, cap ¥45M; lottery" },
    ],
    sections: [
      { id: "top5", h2: "The 5 programs Chinese-owned businesses use most", blocks: [
        { type: "table", head: ["Need", "Program", "Cap / rate", "Type", "Typical use"], rows: [
          ["Equipment, fewer hands", "Labor-Saving Investment Subsidy (general)", "¥7.5M (≤5) to ¥80M (101+) / 1/2 (2/3 small)", "METI, competitive rounds", "Self-ordering, dishwashers, warehouse automation"],
          ["Software, AI, systems", "Digitalization & AI Adoption Subsidy 2026", "¥50k–¥4.5M / up to 1/2", "METI, monthly deadlines, via IT vendor", "Accounting, POS, ERP, e-commerce backend"],
          ["Regularizing part-timers", "Career-Up Grant", "¥200k–¥800k per person", "MHLW, year-round, requirement-based", "Restaurant/retail staff conversion"],
          ["Training", "Human Resource Development Grant", "45–75% + ¥800–1,000/hour", "MHLW, plan-based", "Japanese, skills, DX training"],
          ["Tokyo AC / lighting", "Tokyo Zero-Emission energy-saving grant", "3/4, cap ¥45M", "Tokyo Metro, lottery rounds", "Restaurants, supermarkets, guesthouses"],
        ] },
        { type: "links", items: [{ label: "Labor-Saving Subsidy", href: "/subsidies/seiryoka" }, { label: "AI Adoption Subsidy", href: "/subsidies/ai-it" }, { label: "Career-Up Grant", href: "/subsidies/career-up" }, { label: "HR Development Grant", href: "/subsidies/training" }, { label: "Tokyo AC grant", href: "/subsidies/aircon" }] },
      ] },
      { id: "visa", h2: "Relationship with Business Manager visa and permanent residency", blocks: [
        { type: "p", text: "Reviews look at 'a lawfully operating business in Japan', not nationality. General notes (not legal advice):" },
        { type: "ul", items: [
          "Business Manager visa holders as company representatives: eligible. Compliance items that subsidies check (tax filing, social insurance) overlap with what visa renewal values.",
          "Permanent residents, spouses of Japanese nationals, long-term residents: no restrictions.",
          "Student or dependent status: cannot apply as operators; to be hired and regularized, change to a working status first.",
        ] },
        { type: "note", text: "Subsidy income is taxable business income; plan the booking year with your Zeirishi to avoid surprises at visa renewal." },
      ] },
      { id: "mistakes", h2: "Six common mistakes", blocks: [
        { type: "ol", items: [
          "Buying before applying — only post-decision costs are covered.",
          "Confusing competitive subsidies with requirement-based grants.",
          "Believing 'zero cost' or 'fastest payout' pitches — Tokyo AC is a lottery with co-payment; subsidies reimburse later.",
          "Using unlicensed agents — subsidy documents are Gyoseishoshi work; grant representation is Sharoshi-exclusive.",
          "Preparing documents by home-country habits — Japanese review values plan logic and verifiable numbers.",
          "Relaxing after adoption — non-compliant final reports cut or cancel payment.",
        ] },
      ] },
      { id: "industry", h2: "By industry", blocks: [
        { type: "table", head: ["Industry", "Typical investment", "Priority programs", "Note"], rows: [
          ["Restaurants", "Self-ordering, dishwashers, AC", "Labor-Saving, Tokyo Zero-Emission, Career-Up", "Tokyo AC up to 3/4, lottery"],
          ["Supermarkets / retail", "POS, refrigeration, self-checkout", "Labor-Saving, AI Adoption, Zero-Emission", "Refrigeration counts as energy-saving"],
          ["Beauty / nails / massage", "Booking systems, equipment", "AI Adoption, Sustainability, Career-Up", "Often sole proprietors"],
          ["Trading / cross-border EC", "ERP, warehouse automation", "AI Adoption, Labor-Saving", "Tool must be registered"],
          ["IT / software", "Training, internal systems", "HR Development, AI Adoption", "Reskilling course ends FY2026"],
          ["Care / medical", "Care robots, ICT, training", "Labor-Saving, HR Development, Tokyo care grants", ""],
          ["Guesthouses / hotels", "Self check-in, AC, cleaning robots", "Labor-Saving, Zero-Emission", "Requires lawful lodging license"],
        ] },
        { type: "links", items: [{ label: "Sole proprietors", href: "/for/sole-proprietor" }] },
      ] },
      { id: "how", h2: "Our process and licensed division of work", blocks: [
        { type: "ol", items: [
          "Free diagnosis in Chinese within one business day.",
          "Plan and timeline against the official calendar.",
          "Documents: Gyoseishoshi (subsidy documents), Sharoshi (employment grants), Zeirishi (financials), SME consultant (business plan).",
          "Submission and review follow-up with the secretariat.",
          "Post-adoption: grant decision, compliance during implementation, final report, disbursement. Success-fee basis disclosed before contract.",
        ] },
        { type: "note", text: "We do not guarantee approval. Subsidies are competitive; grants are requirement-based. Outcomes rest with the authority." },
        { type: "links", items: [{ label: "Process & fees", href: "/service" }, { label: "Case studies", href: "/cases" }, { label: "Free diagnosis", href: "/contact" }] },
      ] },
    ],
    faq: [
      { q: "Are foreign-owned companies scored lower?", a: "No. Reviews assess the plan, finances and requirements; nationality is not a factor. Document completeness is where language gaps cost points." },
      { q: "We have no first-year financials yet. Can we apply?", a: "Labor-Saving and AI Adoption have no hard minimum, but financial basis is reviewed; new companies usually start with the Sustainability Subsidy (startup track) or wait for the first closing." },
      { q: "Our staff are Chinese part-timers, some students. Career-Up Grant?", a: "Targets employment-insured staff whose status permits full-time work after conversion. Students must change to a working status first." },
      { q: "Will applying attract tax or immigration scrutiny?", a: "Applications verify tax and social-insurance records — that is compliance itself. Fix arrears or non-enrollment first." },
      { q: "Can we submit in Chinese?", a: "No, all documents must be in Japanese. You communicate in Chinese; licensed professionals produce the Japanese documents." },
      { q: "Is the subsidy taxable?", a: "Yes, as business income. For fixed assets, 圧縮記帳 can defer tax; plan with a Zeirishi." },
      { q: "How are you different from ordinary agents?", a: "Licensed execution across both subsidies and grants; published sources and verification dates for every figure; no approval promises." },
      { q: "We are in Osaka / Nagoya / Fukuoka. Can you help?", a: "Yes. Most programs are national and online. Tokyo-only grants apply to Tokyo sites; local programs are verified case by case." },
    ],
    sources: [
      { label: "Labor-Saving Investment Subsidy", url: SRC.seiryoka },
      { label: "Digitalization & AI Adoption Subsidy 2026", url: SRC.itshien },
      { label: "Career-Up Grant (MHLW)", url: SRC.career },
      { label: "HR Development Grant (MHLW)", url: SRC.jinzai },
      { label: "Tokyo Zero-Emission energy-saving grant", url: SRC.zeroemi },
      { label: "Shisei Consulting corporate record (gBizINFO)", url: SRC.gbizinfo },
    ],
    verifiedDate: VERIFIED,
    related: REL.en,
    ctaTitle1: "Which program fits your business? ",
    ctaTitle2: "Free diagnosis in Chinese",
    ctaDesc: "Four questions — status, industry, headcount, goal. Reply within one business day. No approval, no fee.",
    breadcrumbParent: { label: "Subsidies", href: "/subsidies" },
    ui: UI.en,
  },
  ja: {
    path: "/for/chinese-owners",
    metaTitle: "在日華人経営者向け 補助金・助成金申請サポート｜在留資格・税務・労務まで一体で支援",
    metaDesc: "在日華人が経営する飲食・貿易・美容・小売・IT企業の補助金・助成金申請。よく使われる5制度、経営・管理ビザとの関係、よくある6つの誤解、業種別の入口、中国語対応の士業連携体制を解説。",
    keywords: ["在日華人 補助金", "外国人経営者 補助金", "中国人 経営者 助成金", "中国語対応 補助金 申請サポート", "外国人 会社 補助金 東京"],
    heroEyebrow: "在日華人経営者向け",
    heroTitle1: "外国人経営者の補助金申請に、",
    heroTitle2: "制度も事情も分かるチームを",
    heroDesc: "つまずくのは制度そのものより、言語・書類の習慣・在留資格や税務との連動です。本ページでまとめて整理します。",
    summary: "在日華人の経営者（法人・個人事業主）が申請できる補助金・助成金は日本企業と同一で、国籍要件はありません。必要なのは日本に登記された事業実体、納税申告の実績、事業活動を許可する在留資格です。よく使われる5制度は、中小企業省力化投資補助金一般型（750万〜8,000万円・1/2）、デジタル化・AI導入補助金2026（最大450万円・1/2以内）、キャリアアップ助成金正社員化（1人最大80万円）、人材開発支援助成金（経費助成45〜75%）、東京都ゼロエミ省エネ設備助成（助成率最大3/4・上限4,500万円）。志成コンサル（法人番号5010401158340・東京都千代田区）は行政書士・社会保険労務士・税理士・中小企業診断士の分担体制で、中国語により診断から入金までをサポートします。",
    quickFacts: [
      { label: "国籍要件", value: "なし", sub: "事業実体・納税記録・在留資格で判断" },
      { label: "設備・省人化", value: "省力化 最大8,000万円", sub: "従業員数で5区分；5人以下750万；1/2（小規模2/3）" },
      { label: "システム・AI", value: "AI導入 最大450万円", sub: "1/2以内；IT導入支援事業者経由" },
      { label: "正社員化・訓練", value: "80万円/人・45〜75%", sub: "キャリアアップ／人材開発支援（厚労省）" },
      { label: "東京の空調更新", value: "助成率最大3/4", sub: "ゼロエミ 上限4,500万円；抽選制" },
    ],
    sections: [
      { id: "top5", h2: "華人企業がよく使う5制度", blocks: [
        { type: "table", head: ["ニーズ", "制度", "上限／補助率", "性質", "典型的な活用"], rows: [
          ["設備導入・省人化", "中小企業省力化投資補助事業（一般型）", "5人以下750万〜101人以上8,000万円／1/2（小規模2/3）", "経産省・公募回制・競争採択", "セルフオーダー・食洗機・物流自動化"],
          ["ソフト・AI・システム", "デジタル化・AI導入補助金2026", "5万〜450万円／1/2以内", "経産省・月次締切・IT支援事業者経由", "会計・POS・ERP・越境EC基盤"],
          ["パートの正社員化", "キャリアアップ助成金（正社員化コース）", "1人20万〜80万円", "厚労省・通年・要件支給", "飲食・小売の正社員転換"],
          ["従業員訓練", "人材開発支援助成金", "経費助成45〜75%＋賃金助成800〜1,000円/時", "厚労省・計画届制", "日本語・技能・DX研修"],
          ["東京の空調・照明", "ゼロエミッション化 省エネ設備導入・運用改善支援事業", "3/4・上限4,500万円", "東京都・回次抽選", "飲食店・スーパー・民泊"],
        ] },
        { type: "links", items: [{ label: "省力化補助金", href: "/subsidies/seiryoka" }, { label: "AI導入補助金", href: "/subsidies/ai-it" }, { label: "キャリアアップ助成金", href: "/subsidies/career-up" }, { label: "人材開発支援助成金", href: "/subsidies/training" }, { label: "東京 空調助成", href: "/subsidies/aircon" }] },
      ] },
      { id: "visa", h2: "経営・管理ビザ、永住との関係", blocks: [
        { type: "p", text: "審査は国籍ではなく「日本で適法に事業を営む事業者か」を見ます。一般的な留意点（法的助言ではありません）：" },
        { type: "ul", items: [
          "経営・管理ビザ保有者が法人代表として申請：可能。補助金がビザ審査に影響することはなく、納税・社保加入などの要件はビザ更新で重視される事項と重なります。",
          "永住者・日本人の配偶者等・定住者：制限なし。",
          "留学・家族滞在：経営者としては原則対象外。雇用・正社員化には就労可能な在留資格への変更が先。",
        ] },
        { type: "note", text: "補助金の入金は事業収入（雑収入）として課税対象。計上年度は税理士と事前に計画してください。" },
      ] },
      { id: "mistakes", h2: "よくある6つの誤解", blocks: [
        { type: "ol", items: [
          "先に購入してから申請——交付決定後の支出のみ対象。",
          "「補助金」と「助成金」の混同——前者は競争審査、後者は要件支給。",
          "「実質0円」「最短○か月で入金」を信じる——東京空調は抽選かつ自己負担あり、補助金は後払い。",
          "無資格業者への依頼——補助金書類作成は行政書士、助成金申請代理は社労士の業務。",
          "母国流の書類準備——日本の審査は計画の論理と数字の検証可能性を重視。",
          "採択後の油断——実績報告が不適切なら減額・取消。",
        ] },
      ] },
      { id: "industry", h2: "業種別の入口", blocks: [
        { type: "table", head: ["業種", "典型的な投資", "優先制度", "備考"], rows: [
          ["中華・居酒屋・ラーメン", "セルフオーダー・食洗機・空調", "省力化・東京ゼロエミ・キャリアアップ", "東京の空調は最大3/4、抽選"],
          ["華人スーパー・小売", "POS・冷凍冷蔵・セルフレジ", "省力化・AI導入・ゼロエミ", "冷凍設備は省エネ対象になり得る"],
          ["美容・ネイル・マッサージ", "予約システム・設備", "AI導入・持続化・キャリアアップ", "個人事業主が多い"],
          ["貿易・越境EC", "ERP・倉庫自動化", "AI導入・省力化", "登録ITツールが要件"],
          ["IT・ソフト", "人材育成・社内システム", "人材開発支援・AI導入", "リスキリングコースは令和8年度が最終年度"],
          ["介護・医療", "介護ロボット・ICT・研修", "省力化・人材開発支援・都の介護補助", ""],
          ["民泊・ホテル", "セルフチェックイン・空調・清掃ロボ", "省力化・ゼロエミ", "適法な営業許可が前提"],
        ] },
        { type: "links", items: [{ label: "個人事業主向け", href: "/for/sole-proprietor" }] },
      ] },
      { id: "how", h2: "サポートの流れと士業の分担", blocks: [
        { type: "ol", items: [
          "無料診断（中国語・1営業日以内）。",
          "公募カレンダーに基づく計画とスケジュール。",
          "書類作成：行政書士（補助金書類）、社労士（雇用関係助成金）、税理士（財務）、中小企業診断士（事業計画）。",
          "提出と審査対応。",
          "採択後：交付決定・実施中のコンプライアンス・実績報告・入金確認。成功報酬制、料率は契約前に書面提示。",
        ] },
        { type: "note", text: "採択を保証することはありません。補助金は競争審査、助成金は要件審査であり、結果は主管機関の判断によります。" },
        { type: "links", items: [{ label: "サービスの流れ・費用", href: "/service" }, { label: "導入事例", href: "/cases" }, { label: "無料診断", href: "/contact" }] },
      ] },
    ],
    faq: [
      { q: "外国人経営の会社は審査で不利になりますか？", a: "なりません。審査は事業計画・財務・要件に基づき、国籍は評価項目ではありません。差が出るのは書類の完成度です。" },
      { q: "設立直後で第1期決算がありません。申請できますか？", a: "省力化・AI導入に年数要件はありませんが財務基盤が審査されます。新設法人は持続化補助金（創業型）や第1期決算後の申請が現実的です。" },
      { q: "従業員が華人のパート・留学生ですが、キャリアアップ助成金は使えますか？", a: "雇用保険被保険者で、転換後に就労可能な在留資格を持つ方が対象です。留学生は就労資格への変更が先です。" },
      { q: "申請すると税務署や入管に注目されませんか？", a: "申請では納税・社保記録が確認されます。滞納や未加入があれば先に是正してください。" },
      { q: "中国語で書類を提出できますか？", a: "できません。すべて日本語です。お客様は中国語で情報提供いただき、日本語書類は有資格者が作成します。" },
      { q: "補助金に税金はかかりますか？", a: "かかります。事業収入として課税。固定資産は圧縮記帳で繰延可能、税理士と計画してください。" },
      { q: "一般の仲介業者との違いは？", a: "士業による適法な分担執行、全数値に出典と確認日を明記、採択の約束をしないことです。" },
      { q: "大阪・名古屋・福岡でも依頼できますか？", a: "可能です。多くは全国制度でオンライン完結。東京都独自助成は都内事業所限定、地方制度は個別に確認します。" },
    ],
    sources: [
      { label: "中小企業省力化投資補助事業（一般型）", url: SRC.seiryoka },
      { label: "デジタル化・AI導入補助金2026", url: SRC.itshien },
      { label: "キャリアアップ助成金（厚生労働省）", url: SRC.career },
      { label: "人材開発支援助成金（厚生労働省）", url: SRC.jinzai },
      { label: "東京都 ゼロエミッション化 省エネ設備導入支援事業", url: SRC.zeroemi },
      { label: "株式会社志成コンサル 法人情報（GビズINFO）", url: SRC.gbizinfo },
    ],
    verifiedDate: VERIFIED,
    related: REL.ja,
    ctaTitle1: "貴社に合う制度は？ ",
    ctaTitle2: "中国語で無料診断",
    ctaDesc: "在留資格・業種・従業員数・目的の4項目で、1営業日以内に申請可能な制度と準備事項をご回答。不採択なら費用はいただきません。",
    breadcrumbParent: { label: "補助金の種類", href: "/subsidies" },
    ui: UI.ja,
  },
};
