import type { PillarSet } from "./types";
import { UI } from "./types";

const VERIFIED = "2026-09-03";
const SRC = {
  chusho: "https://www.chusho.meti.go.jp/keiei/koukai/index.html",
  mhlw: "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/koyou/kyufukin/index.html",
  jfc: "https://www.jfc.go.jp/n/finance/search/index.html",
  jgrants: "https://www.jgrants-portal.go.jp/",
  seiryoka: "https://shoryokuka.smrj.go.jp/ippan/",
  career: "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/part_haken/jigyounushi/career.html",
};
const REL = {
  zh: [
    { label: "个人事业主可申请的补助金", href: "/for/sole-proprietor" },
    { label: "在日华人企业主专题", href: "/for/chinese-owners" },
    { label: "2026 公募日历", href: "/schedule" },
    { label: "省力化補助金详解", href: "/subsidies/seiryoka" },
    { label: "转正助成金详解", href: "/subsidies/career-up" },
  ],
  en: [
    { label: "Sole proprietors", href: "/for/sole-proprietor" },
    { label: "Chinese business owners", href: "/for/chinese-owners" },
    { label: "2026 calendar", href: "/schedule" },
    { label: "Labor-Saving Subsidy", href: "/subsidies/seiryoka" },
    { label: "Career-Up Grant", href: "/subsidies/career-up" },
  ],
  ja: [
    { label: "個人事業主向け", href: "/for/sole-proprietor" },
    { label: "在日華人経営者向け", href: "/for/chinese-owners" },
    { label: "2026年 公募カレンダー", href: "/schedule" },
    { label: "省力化補助金", href: "/subsidies/seiryoka" },
    { label: "キャリアアップ助成金", href: "/subsidies/career-up" },
  ],
};

export const compare: PillarSet = {
  zh: {
    path: "/compare",
    metaTitle: "补助金和助成金有什么区别？在日华人企业主一张表看懂（含融资·减税对比）",
    metaDesc: "補助金（経産省系·竞争採択·公募回制）与助成金（厚労省系·要件支给·通年受付）的 8 项核心区别，加上与日本政策金融公库融资、税制优惠的横向对比。哪种适合买设备、哪种适合雇人、能否叠加、哪种先做——一张表说清。",
    keywords: ["补助金 助成金 区别", "補助金 助成金 違い", "补助金 是什么", "助成金 要还吗", "补助金 融资 区别", "日本 补助金 助成金 哪个好"],
    heroEyebrow: "对比决策",
    heroTitle1: "补助金 vs 助成金：",
    heroTitle2: "一张表看懂区别与选法",
    heroDesc: "很多在日华人把「補助金」「助成金」混着说，但两者从主管部门、审查方式到时间节奏完全不同。选错路线，最常见的结果是白准备半年。",
    summary: "在日本，「補助金（ほじょきん）」多由経済産業省·中小企業庁及地方政府发放，采用公募回制与竞争审查，符合条件也可能不採択，典型如省力化投資補助金、デジタル化・AI導入補助金、持続化補助金；「助成金（じょせいきん）」多由厚生労働省发放，以雇用·劳务为对象，要件满足原则支给、通年受付，典型如キャリアアップ助成金、人材開発支援助成金。两者都不需返还（合规前提下），都是事后支付，同一费用不可重复领取。买设备上系统走補助金，雇人转正培训走助成金，两条线可以并行规划。",
    quickFacts: [
      { label: "補助金 主管", value: "経産省·中小企業庁·地方政府", sub: "设备·系统·创业·贩路开拓" },
      { label: "助成金 主管", value: "厚生労働省", sub: "雇用·转正·培训·劳务环境" },
      { label: "审查方式", value: "竞争採択 vs 要件支给", sub: "補助金可能不採択；助成金满足要件原则支给" },
      { label: "受付", value: "公募回制 vs 通年", sub: "補助金有截止日；助成金随时可申请（需事前计划届）" },
      { label: "是否返还", value: "都不需返还", sub: "合规前提下；违规·未达成有返还风险" },
    ],
    sections: [
      {
        id: "table",
        h2: "8 项核心区别一览",
        blocks: [
          { type: "table", caption: "一般性对照；个别制度有例外，以各公募要領为准", head: ["对比项", "補助金（补助金）", "助成金（助成金）"], rows: [
            ["主管部门", "経済産業省·中小企業庁、各都道府县·市区", "厚生労働省（都道府县劳动局·ハローワーク窗口）"],
            ["目的", "设备投资、数字化、创业、新事业、贩路开拓、节能", "雇用促进、正社员化、员工培训、劳务环境改善"],
            ["审查方式", "竞争審査·採択制：按事业计划评分排序，预算内择优", "要件審査：满足要件原则支给"],
            ["受付时间", "公募回制，有明确締切；错过等下一回", "通年受付；但多数需在实施前提交计划届"],
            ["金额级别", "数十万〜数千万円（省力化最高 8,000 万）", "数十万〜数百万円/人或/事业所（人材開発特定コース更高）"],
            ["经费范围", "广：设备、软件、外注、广告、改装等", "窄：与雇用·培训直接相关的赁金·经费"],
            ["支付时点", "事后：交付決定→实施→实绩报告→审核→入金", "事后：实施→支給申请→审核→入金"],
            ["谁能代办", "书类作成代行属行政書士；认定支援机关出确认书", "申请代理属社会保険労務士专属业务"],
          ] },
          { type: "note", text: "两者共同点：都是「先花钱后拿钱」、都要纳税（雑収入）、同一费用不可重复受领、违规或未达成计划都有返还风险。" },
        ],
      },
      {
        id: "which",
        h2: "你的需求该走哪条线",
        blocks: [
          { type: "table", head: ["我想做的事", "走哪条线", "代表制度", "备注"], rows: [
            ["买自动化设备、机器人", "補助金", "省力化投資補助金（一般型）", "5 人以下 750 万〜101 人以上 8,000 万；1/2（小規模 2/3）"],
            ["上会计/POS/预约/AI 系统", "補助金", "デジタル化・AI導入補助金2026", "最高 450 万；须经 IT 導入支援事業者"],
            ["做官网、投广告、店铺改装", "補助金", "小規模事業者持続化補助金", "通常枠 50 万·2/3；商業服务业 ≤5 人"],
            ["东京店铺换空调、照明", "補助金（都独自）", "ゼロエミ 省エネ設備導入支援事業", "助成率最高 3/4；名字叫助成但属都补助制度，抽签制"],
            ["兼职/有期员工转正", "助成金", "キャリアアップ助成金 正社員化コース", "每人 20〜80 万；转正前提交計画届"],
            ["给员工做培训", "助成金", "人材開発支援助成金", "经费 45〜75% + 赁金 800〜1,000 円/h"],
            ["雇用高龄/障害/母子家庭", "助成金", "特定求職者雇用開発助成金", "按对象·期间分档"],
          ] },
          { type: "links", items: [{ label: "个人事业主专题", href: "/for/sole-proprietor" }, { label: "在日华人企业主专题", href: "/for/chinese-owners" }] },
        ],
      },
      {
        id: "stack",
        h2: "能不能叠加？两条线并行的正确姿势",
        blocks: [
          { type: "p", text: "可以并行，但要遵守三个原则：" },
          { type: "ol", items: [
            "不同费用可以分走不同制度：设备走省力化、转正走キャリアアップ——费用对象不同，不冲突。",
            "同一费用只能领一次：例如同一套系统不能同时报 AI導入補助金与持続化補助金。",
            "时间要错开安排：助成金需实施前计划届，補助金需交付決定后才能签约——两条线的「起点」不同，日程表要分别倒推。",
          ] },
          { type: "note", text: "常见组合：餐饮店「省力化（自动点餐）+ キャリアアップ（兼职转正）+ 东京ゼロエミ（空调）」三线并行，分别对应设备、人、能源三类支出。" },
        ],
      },
      {
        id: "vs-loan",
        h2: "补助金·助成金 vs 融资 vs 税制优惠",
        blocks: [
          { type: "table", head: ["", "補助金/助成金", "政策融资（日本政策金融公庫等）", "税制优惠（中小企業経営強化税制等）"], rows: [
            ["要不要还", "不用（合规前提）", "要，含利息", "不涉及现金，减少税额"],
            ["拿到时间", "事后 6〜12 个月", "审批后 1〜2 个月放款", "决算申告时体现"],
            ["用途限制", "严格限定于申请事业", "较灵活（设备·运转资金）", "限定对象设备"],
            ["审查难度", "補助金竞争、助成金要件", "看信用与返还能力", "满足要件即可"],
            ["适合", "有明确投资计划、能等待", "需要马上有钱周转", "有利润、需减税"],
          ] },
          { type: "p", text: "实务上三者常组合使用：先用融资垫付设备款（补助金后付），拿到补助金后部分偿还，购入设备同时适用即时偿却或税额控除。具体组合需税理士与融资顾问共同规划。" },
        ],
      },
      {
        id: "terms",
        h2: "必须分清的 6 个术语",
        blocks: [
          { type: "table", head: ["术语", "含义", "常见误解"], rows: [
            ["採択（さいたく）", "補助金审查通过、进入候选", "≠ 拿到钱；之后还要交付申请"],
            ["交付決定（こうふけってい）", "正式批准补助、可开始签约支出", "在此之前签约付款不算可经费"],
            ["実績報告（じっせきほうこく）", "事业完成后提交的报告", "不合规会减额或取消"],
            ["支給決定（しきゅうけってい）", "助成金审核通过、决定支付", "助成金专用术语，与「交付決定」对应"],
            ["不採択（ふさいたく）", "補助金审查未通过", "可下回再报，无惩罚"],
            ["返還（へんかん）", "违规或未达成计划时退回补助", "非「补助金要还」，合规就不需还"],
          ] },
        ],
      },
    ],
    faq: [
      { q: "补助金和助成金都不用还吗？", a: "在合规前提下都不需要返还。但若虚假申报、未按计划实施、擅自处分补助财产（如在处分制限期间内卖掉补助购入的设备），会被要求返还并可能加算金。" },
      { q: "哪个更容易拿到？", a: "助成金是要件审查，满足要件原则支给，确定性高；補助金是竞争採択，全国採択率因制度与回次不同，大致 3〜7 成波动。但「容易」不等于「适合」——两者对象不同，不是替代关系。" },
      { q: "个人事业主两种都能申请吗？", a: "補助金可以（持続化、AI導入、省力化均含個人事業主）；助成金要求有雇用保险被保险者，一人经营没有员工则申请不了。" },
      { q: "东京都的「〇〇助成金」是助成金还是补助金？", a: "地方政府常把自己的补助制度叫「助成金」「助成事業」，本质多属补助金性质（有公募·有审查或抽签）。判断性质看审查方式，不看名字。" },
      { q: "可以同时申请国家补助金和东京都助成吗？", a: "可以，但同一费用不能重复受领。多数东京都制度写明「国等の補助金との併用不可（同一経費）」。分开费用即可并行。" },
      { q: "找谁代办才合法？", a: "補助金申请书类的有偿作成属行政書士业务（部分制度还需认定経営革新等支援機関确认）；助成金的申请代理是社会保険労務士的独占业务。志成由对应持牌人分工执行。" },
      { q: "補助金採択后多久能拿到钱？", a: "採択→交付決定約 1〜2 个月→事业实施（数月）→实绩报告→审核→入金，整体 6〜12 个月。助成金从实施到入金通常 3〜6 个月。" },
      { q: "两条线都想做，先做哪个？", a: "先看截止：補助金有公募締切，先锁定日程；助成金通年但需实施前计划届，可与補助金并行准备。免费诊断时我们会给出两条线的合并时间表。" },
    ],
    sources: [
      { label: "中小企業庁 補助金・公募情報", url: SRC.chusho },
      { label: "厚生労働省 雇用関係助成金一覧", url: SRC.mhlw },
      { label: "jGrants 補助金電子申請システム", url: SRC.jgrants },
      { label: "日本政策金融公庫 融資制度", url: SRC.jfc },
      { label: "中小企業省力化投資補助事業（一般型）", url: SRC.seiryoka },
      { label: "キャリアアップ助成金", url: SRC.career },
    ],
    verifiedDate: VERIFIED,
    related: REL.zh,
    ctaTitle1: "不确定走哪条线？",
    ctaTitle2: "让我们帮你判断",
    ctaDesc: "告诉我们想做的事与员工数，1 个营业日内回复「補助金还是助成金、能否并行、先做哪个」。免费，不获批不收费。",
    breadcrumbParent: { label: "补助金种类", href: "/subsidies" },
    ui: UI.zh,
  },
  en: {
    path: "/compare",
    metaTitle: "Hojokin vs. Joseikin: Japanese Subsidies and Grants Compared (Plus Loans & Tax Incentives)",
    metaDesc: "Eight key differences between METI subsidies (competitive, round-based) and MHLW grants (requirement-based, year-round), plus a comparison with policy loans and tax incentives. Which fits equipment, which fits hiring, whether they stack.",
    keywords: ["hojokin joseikin difference", "Japan subsidy vs grant", "Japanese government subsidy types"],
    heroEyebrow: "Decision guide",
    heroTitle1: "Subsidy vs. grant in Japan:",
    heroTitle2: "the differences in one table",
    heroDesc: "'Hojokin' and 'joseikin' are often used interchangeably, but they differ in ministry, review method and timing. Choosing the wrong track usually wastes six months of preparation.",
    summary: "In Japan, 'hojokin' (subsidies) are mostly issued by METI/SME Agency and local governments through competitive, round-based reviews — eligibility does not guarantee adoption (e.g., Labor-Saving, AI Adoption, Sustainability). 'Joseikin' (grants) are mostly issued by MHLW for employment matters, paid when requirements are met, accepted year-round (e.g., Career-Up, HR Development). Neither is repaid if compliant; both pay after the fact; the same cost cannot be claimed twice. Equipment and systems → subsidies; hiring and training → grants; the two tracks can run in parallel.",
    quickFacts: [
      { label: "Subsidies (hojokin)", value: "METI / local gov.", sub: "Equipment, systems, startup, marketing" },
      { label: "Grants (joseikin)", value: "MHLW", sub: "Hiring, regularization, training" },
      { label: "Review", value: "Competitive vs. requirement", sub: "Subsidies can be rejected; grants paid if requirements met" },
      { label: "Window", value: "Rounds vs. year-round", sub: "Subsidies have deadlines; grants need prior plan filing" },
      { label: "Repayment", value: "None if compliant", sub: "Repayment risk on violation or non-achievement" },
    ],
    sections: [
      { id: "table", h2: "Eight key differences", blocks: [
        { type: "table", head: ["Item", "Subsidy (hojokin)", "Grant (joseikin)"], rows: [
          ["Ministry", "METI / SME Agency, prefectures & cities", "MHLW (labor bureaus, Hello Work)"],
          ["Purpose", "Investment, digitalization, startup, marketing, energy", "Hiring, regularization, training, workplace"],
          ["Review", "Competitive scoring within budget", "Requirement check"],
          ["Window", "Rounds with deadlines", "Year-round; plan filed before implementation"],
          ["Amount", "¥100k–¥80M", "¥100k–several million per person/site"],
          ["Eligible costs", "Broad", "Narrow: wages and training costs"],
          ["Payment", "After final report", "After payment application"],
          ["Who may represent", "Gyoseishoshi (documents)", "Sharoshi (exclusive)"],
        ] },
        { type: "note", text: "Common to both: pay first, reimbursed later; taxable; no double claiming; repayment risk on violation." },
      ] },
      { id: "which", h2: "Which track for your need", blocks: [
        { type: "table", head: ["Goal", "Track", "Program", "Note"], rows: [
          ["Automation equipment", "Subsidy", "Labor-Saving Investment Subsidy", "¥7.5M–¥80M; 1/2 (2/3 small)"],
          ["Accounting/POS/AI systems", "Subsidy", "Digitalization & AI Adoption 2026", "Up to ¥4.5M; via IT vendor"],
          ["Website, ads, renovation", "Subsidy", "Small Business Sustainability", "¥500k, 2/3"],
          ["Tokyo AC / lighting", "Subsidy (Tokyo)", "Zero-Emission energy-saving", "Up to 3/4; lottery"],
          ["Regularize part-timers", "Grant", "Career-Up Grant", "¥200k–¥800k per person"],
          ["Staff training", "Grant", "HR Development Grant", "45–75% + hourly wage support"],
        ] },
        { type: "links", items: [{ label: "Sole proprietors", href: "/for/sole-proprietor" }, { label: "Chinese business owners", href: "/for/chinese-owners" }] },
      ] },
      { id: "stack", h2: "Can they stack?", blocks: [
        { type: "ol", items: [
          "Different costs can go to different programs.",
          "The same cost can be claimed only once.",
          "Timelines differ: grants need a plan before implementation; subsidies allow contracts only after the grant decision.",
        ] },
      ] },
      { id: "vs-loan", h2: "Versus policy loans and tax incentives", blocks: [
        { type: "table", head: ["", "Subsidy/grant", "Policy loan (JFC)", "Tax incentive"], rows: [
          ["Repay?", "No (if compliant)", "Yes, with interest", "No cash; reduces tax"],
          ["Timing", "6–12 months after", "1–2 months", "At tax filing"],
          ["Use", "Strictly the approved project", "Flexible", "Designated assets"],
          ["Review", "Competitive / requirement", "Creditworthiness", "Requirements"],
        ] },
        { type: "p", text: "Often combined: a loan bridges the equipment cost, the subsidy repays part of it, and the asset qualifies for immediate depreciation or tax credit." },
      ] },
      { id: "terms", h2: "Six terms to know", blocks: [
        { type: "table", head: ["Term", "Meaning", "Misconception"], rows: [
          ["採択 (adoption)", "Passed review", "Not yet money"],
          ["交付決定 (grant decision)", "Formal approval; contracts may start", "Costs before this are ineligible"],
          ["実績報告 (final report)", "Post-project report", "Non-compliance cuts payment"],
          ["支給決定 (payment decision)", "Grant approved for payment", "Grant-side equivalent"],
          ["不採択 (rejection)", "Failed competitive review", "Can reapply"],
          ["返還 (repayment)", "Return on violation", "Not routine repayment"],
        ] },
      ] },
    ],
    faq: [
      { q: "Are both non-repayable?", a: "Yes if compliant. False claims, unimplemented plans or disposing of subsidized assets during the restriction period trigger repayment." },
      { q: "Which is easier?", a: "Grants are requirement-based, so more certain; subsidy adoption rates vary roughly 30–70% by program and round. But they target different needs." },
      { q: "Can sole proprietors use both?", a: "Subsidies yes; grants require employment-insured staff." },
      { q: "Is a Tokyo '助成金' a grant or subsidy?", a: "Local governments call their subsidies 'joseikin', but most are competitive or lottery-based subsidies in nature." },
      { q: "National subsidy plus Tokyo grant together?", a: "Yes for different costs; the same cost cannot be claimed twice." },
      { q: "Who can legally represent me?", a: "Subsidy documents: Gyoseishoshi; grant representation: Sharoshi exclusively." },
      { q: "How long until payment?", a: "Subsidies 6–12 months; grants 3–6 months after implementation." },
      { q: "Which first?", a: "Lock subsidy deadlines first; prepare grant plans in parallel." },
    ],
    sources: [
      { label: "SME Agency subsidy information", url: SRC.chusho },
      { label: "MHLW employment grants", url: SRC.mhlw },
      { label: "jGrants", url: SRC.jgrants },
      { label: "Japan Finance Corporation", url: SRC.jfc },
    ],
    verifiedDate: VERIFIED,
    related: REL.en,
    ctaTitle1: "Not sure which track? ",
    ctaTitle2: "Let us assess",
    ctaDesc: "Tell us your goal and headcount; we reply within one business day. Free; no approval, no fee.",
    breadcrumbParent: { label: "Subsidies", href: "/subsidies" },
    ui: UI.en,
  },
  ja: {
    path: "/compare",
    metaTitle: "補助金と助成金の違いを一覧表で解説｜融資・税制優遇との比較も（2026）",
    metaDesc: "補助金（経産省系・競争採択・公募回制）と助成金（厚労省系・要件支給・通年受付）の8つの違いに加え、日本政策金融公庫の融資や税制優遇との横比較。設備投資はどちらか、雇用はどちらか、併用の可否を整理。",
    keywords: ["補助金 助成金 違い", "補助金とは", "助成金とは", "補助金 融資 違い", "補助金 助成金 併用"],
    heroEyebrow: "比較・判断",
    heroTitle1: "補助金と助成金：",
    heroTitle2: "違いと選び方を一覧表で",
    heroDesc: "混同されがちな「補助金」と「助成金」は、主管省庁・審査方法・時期がまったく異なります。路線を誤ると半年の準備が無駄になります。",
    summary: "日本の「補助金」は主に経済産業省・中小企業庁および地方自治体が交付し、公募回制・競争審査のため要件を満たしても不採択になり得ます（省力化投資補助金、デジタル化・AI導入補助金、持続化補助金など）。「助成金」は主に厚生労働省が雇用・労務を対象に交付し、要件を満たせば原則支給・通年受付です（キャリアアップ助成金、人材開発支援助成金など）。いずれも適法であれば返還不要、後払い、同一経費の重複受給不可。設備・システムは補助金、雇用・正社員化・訓練は助成金で、両者は並行して計画できます。",
    quickFacts: [
      { label: "補助金の主管", value: "経産省・中小企業庁・自治体", sub: "設備・システム・創業・販路開拓" },
      { label: "助成金の主管", value: "厚生労働省", sub: "雇用・正社員化・訓練・労務環境" },
      { label: "審査", value: "競争採択 vs 要件支給", sub: "補助金は不採択あり；助成金は要件充足で原則支給" },
      { label: "受付", value: "公募回制 vs 通年", sub: "補助金は締切あり；助成金は事前の計画届" },
      { label: "返還", value: "いずれも不要", sub: "適法な場合；違反・未達で返還リスク" },
    ],
    sections: [
      { id: "table", h2: "8つの主な違い", blocks: [
        { type: "table", head: ["項目", "補助金", "助成金"], rows: [
          ["主管", "経済産業省・中小企業庁、都道府県・市区", "厚生労働省（労働局・ハローワーク）"],
          ["目的", "設備投資・デジタル化・創業・販路開拓・省エネ", "雇用促進・正社員化・訓練・労務環境改善"],
          ["審査", "競争審査・採択制", "要件審査"],
          ["受付", "公募回制・締切あり", "通年；多くは実施前に計画届"],
          ["金額", "数十万〜数千万円（省力化最大8,000万）", "数十万〜数百万円/人・事業所"],
          ["対象経費", "広い", "狭い（賃金・訓練経費）"],
          ["支払時期", "実績報告後", "支給申請後"],
          ["代理できる者", "書類作成は行政書士", "申請代理は社労士の独占業務"],
        ] },
        { type: "note", text: "共通点：後払い、課税対象、同一経費の重複不可、違反時の返還リスク。" },
      ] },
      { id: "which", h2: "目的別の路線", blocks: [
        { type: "table", head: ["やりたいこと", "路線", "代表制度", "備考"], rows: [
          ["自動化設備・ロボット", "補助金", "省力化投資補助金（一般型）", "750万〜8,000万；1/2（小規模2/3）"],
          ["会計・POS・予約・AI", "補助金", "デジタル化・AI導入補助金2026", "最大450万；IT支援事業者経由"],
          ["Web・広告・店舗改装", "補助金", "小規模事業者持続化補助金", "通常枠50万・2/3"],
          ["東京の空調・照明", "補助金（都）", "ゼロエミ 省エネ設備導入支援", "最大3/4；抽選"],
          ["パート・有期の正社員化", "助成金", "キャリアアップ助成金", "1人20〜80万"],
          ["従業員訓練", "助成金", "人材開発支援助成金", "経費45〜75%＋賃金助成"],
        ] },
        { type: "links", items: [{ label: "個人事業主向け", href: "/for/sole-proprietor" }, { label: "在日華人経営者向け", href: "/for/chinese-owners" }] },
      ] },
      { id: "stack", h2: "併用できますか？", blocks: [
        { type: "ol", items: [
          "異なる経費は異なる制度に振り分け可能。",
          "同一経費は1回のみ。",
          "時期が異なる：助成金は実施前の計画届、補助金は交付決定後に契約。",
        ] },
      ] },
      { id: "vs-loan", h2: "融資・税制優遇との比較", blocks: [
        { type: "table", head: ["", "補助金・助成金", "政策融資（公庫等）", "税制優遇"], rows: [
          ["返済", "不要（適法時）", "要・利息あり", "現金なし・税額減"],
          ["時期", "事後6〜12か月", "1〜2か月", "申告時"],
          ["用途", "申請事業に限定", "比較的柔軟", "対象設備限定"],
          ["審査", "競争／要件", "信用力", "要件"],
        ] },
        { type: "p", text: "実務では、融資で設備代を立て替え、補助金受給後に一部返済、設備は即時償却・税額控除を適用という組み合わせが一般的です。" },
      ] },
      { id: "terms", h2: "押さえるべき6つの用語", blocks: [
        { type: "table", head: ["用語", "意味", "誤解"], rows: [
          ["採択", "審査通過", "＝入金ではない"],
          ["交付決定", "正式承認・契約開始可", "これ以前の支出は対象外"],
          ["実績報告", "事業完了後の報告", "不備で減額・取消"],
          ["支給決定", "助成金の支払決定", "助成金側の用語"],
          ["不採択", "審査不通過", "再申請可"],
          ["返還", "違反時の返金", "通常は返還不要"],
        ] },
      ] },
    ],
    faq: [
      { q: "どちらも返還不要ですか？", a: "適法であれば不要です。虚偽申請・計画未実施・処分制限期間内の資産処分などは返還対象です。" },
      { q: "どちらが取りやすいですか？", a: "助成金は要件審査で確度が高く、補助金の採択率は制度・回次で概ね3〜7割。ただし対象が異なり代替関係ではありません。" },
      { q: "個人事業主は両方使えますか？", a: "補助金は可能。助成金は雇用保険被保険者が必要です。" },
      { q: "東京都の「助成金」は助成金ですか？", a: "自治体は自らの補助制度を「助成金」と呼ぶことが多く、性質は競争・抽選型の補助金に近いものが多いです。" },
      { q: "国の補助金と都の助成の併用は？", a: "経費が異なれば可能。同一経費の重複は不可。" },
      { q: "誰に依頼すれば適法ですか？", a: "補助金書類は行政書士、助成金申請代理は社労士の独占業務です。" },
      { q: "入金までの期間は？", a: "補助金6〜12か月、助成金は実施後3〜6か月が一般的。" },
      { q: "どちらを先に？", a: "補助金の締切を先に確保し、助成金の計画届を並行準備。" },
    ],
    sources: [
      { label: "中小企業庁 補助金・公募情報", url: SRC.chusho },
      { label: "厚生労働省 雇用関係助成金", url: SRC.mhlw },
      { label: "jGrants", url: SRC.jgrants },
      { label: "日本政策金融公庫", url: SRC.jfc },
    ],
    verifiedDate: VERIFIED,
    related: REL.ja,
    ctaTitle1: "どちらの路線か迷ったら ",
    ctaTitle2: "無料で判断します",
    ctaDesc: "目的と従業員数をお知らせください。1営業日以内に「補助金か助成金か、併用可否、優先順」をご回答。不採択なら費用はいただきません。",
    breadcrumbParent: { label: "補助金の種類", href: "/subsidies" },
    ui: UI.ja,
  },
};
