import type { PillarSet } from "./types";
import { UI } from "./types";

const SRC = {
  jizokuka: "https://r6.jizokukahojokin.info/",
  itshien: "https://it-shien.smrj.go.jp/",
  seiryoka: "https://shoryokuka.smrj.go.jp/ippan/",
  career: "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/part_haken/jigyounushi/career.html",
  jinzai: "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/koyou/kyufukin/d01-1.html",
  kosha: "https://www.tokyo-kosha.or.jp/support/josei/index.html",
  gbiz: "https://gbiz-id.go.jp/",
};
const VERIFIED = "2026-09-03";
const RELATED = {
  zh: [
    { label: "补助金 vs 助成金 一张表看懂", href: "/compare" },
    { label: "2026 公募日历与截止时间", href: "/schedule" },
    { label: "デジタル化・AI導入補助金2026 详解", href: "/subsidies/ai-it" },
    { label: "省力化投資補助金（一般型）详解", href: "/subsidies/seiryoka" },
    { label: "在日华人企业主专题", href: "/for/chinese-owners" },
  ],
  en: [
    { label: "Subsidy vs. grant: the differences", href: "/compare" },
    { label: "2026 application calendar", href: "/schedule" },
    { label: "Digitalization & AI Adoption Subsidy 2026", href: "/subsidies/ai-it" },
    { label: "Labor-Saving Investment Subsidy", href: "/subsidies/seiryoka" },
    { label: "For Chinese business owners in Japan", href: "/for/chinese-owners" },
  ],
  ja: [
    { label: "補助金と助成金の違い（一覧表）", href: "/compare" },
    { label: "2026年 公募カレンダー・締切", href: "/schedule" },
    { label: "デジタル化・AI導入補助金2026", href: "/subsidies/ai-it" },
    { label: "中小企業省力化投資補助金（一般型）", href: "/subsidies/seiryoka" },
    { label: "在日華人経営者向けページ", href: "/for/chinese-owners" },
  ],
};

export const soleProprietor: PillarSet = {
  zh: {
    path: "/for/sole-proprietor",
    metaTitle: "个人事业主能申请哪些日本补助金？2026 可申请清单、条件与常见误区",
    metaDesc: "在日个人事业主（個人事業主）也能申请日本补助金·助成金：小規模事業者持続化補助金、デジタル化・AI導入補助金2026、省力化投資補助金、东京都助成金，以及雇人后可用的キャリアアップ助成金。逐项说明条件、金额、准备清单与中文申请支持。",
    keywords: ["个人事业主 补助金", "個人事業主 補助金", "日本 个体户 补助金", "自雇 助成金 日本", "小規模事業者持続化補助金 个人事业主", "在日华人 个人事业主 补助金"],
    heroEyebrow: "个人事业主专题",
    heroTitle1: "个人事业主也能申请的",
    heroTitle2: "日本补助金·助成金清单（2026）",
    heroDesc: "没有法人、没有员工，也有能申请的制度。本页只讲个人事业主（個人事業主）真正用得上的几项：谁能申请、能拿多少、什么时候报、需要提前准备什么。",
    summary: "在日本以個人事業主身份经营的在日华人，可申请的主要制度有四类：①小規模事業者持続化補助金（通常枠上限 50 万円、补助率 2/3，特例最高 200 万円）；②デジタル化・AI導入補助金2026（通常枠 5 万〜450 万円、补助率 1/2 以内）；③中小企業省力化投資補助金一般型（5 人以下上限 750 万円、补助率 1/2，小規模事業者 2/3）；④东京都中小企業振興公社等地方助成金。雇用员工后还可申请キャリアアップ助成金（正社員化每人最高 80 万円）。前提是已提交開業届、有確定申告记录，并取得 GビズID。",
    quickFacts: [
      { label: "最常用制度", value: "持続化補助金", sub: "通常枠上限 50 万円·补助率 2/3；第 20 回受付 2026-11-05〜12-15" },
      { label: "上系统/软件", value: "AI導入補助金 最高 450 万円", sub: "补助率 1/2 以内；须经 IT 導入支援事業者共同申请" },
      { label: "买设备", value: "省力化 一般型 750 万円", sub: "5 人以下档；补助率 1/2（小規模 2/3）" },
      { label: "雇人后", value: "転正每人最高 80 万円", sub: "キャリアアップ助成金 正社員化コース，通年受付" },
    ],
    sections: [
      {
        id: "can-i-apply",
        h2: "先回答三个最常问的问题",
        blocks: [
          { type: "h3", text: "① 个人事业主（没有法人）能申请补助金吗？" },
          { type: "p", text: "能。日本绝大多数面向「中小企業者・小規模事業者」的补助金，定义里都明确包含個人事業主。判断资格看的不是有没有株式会社，而是：是否在日本有事业实体（開業届）、是否按期確定申告、所属行业和常时雇用人数是否在制度规定范围内。" },
          { type: "h3", text: "② 一个人经营、没有员工，能拿助成金吗？" },
          { type: "p", text: "厚生労働省系的「助成金」（キャリアアップ助成金、人材開発支援助成金等）以雇用关系为前提，没有雇用保险被保险者的一人经营者原则上申请不了。但経済産業省系的「補助金」（持続化、AI導入、省力化）不要求有员工，一人也能报。想用助成金，先合规雇人（加入雇用保险）再规划。" },
          { type: "h3", text: "③ 刚开业多久可以申请？" },
          { type: "p", text: "持続化補助金要求申请时已開業且能提交確定申告書（创业未满一年可用開業届替代，具体按当回公募要領）；AI導入補助金与省力化補助金没有硬性经营年限，但审查看事业计划与财务数据，有 1 期以上申告记录通常更稳。" },
        ],
      },
      {
        id: "list",
        h2: "2026 年个人事业主可申请的制度一览",
        blocks: [
          {
            type: "table",
            caption: "金额·补助率以各制度官方公募要領为准（核验日 2026-09-03）",
            head: ["制度（日文正式名）", "适合做什么", "上限 / 补助率", "受付方式", "有无员工要求"],
            rows: [
              ["小規模事業者持続化補助金〈一般型 通常枠〉", "开拓客源：网站、宣传、店铺改装、展会", "50 万円 / 2/3（赁金引上等特例最高 200 万円，インボイス特例 +50 万円）", "公募回制；第 20 回受付 2026-11-05〜12-15 17:00，様式4 发行截止 12-04", "无（商业·服务业常时员工 ≤5 人）"],
              ["デジタル化・AI導入補助金2026（旧 IT導入補助金）", "上会计/预约/POS/AI 工具、系统", "通常枠 5 万〜450 万円 / 1/2 以内（满足最低工资要件 2/3）", "按月轮次締切；须与登记的 IT 導入支援事業者共同申请", "无"],
              ["中小企業省力化投資補助事業（一般型）", "买自动化设备、省人化系统", "5 人以下 750 万円（大幅涨薪特例 1,000 万）/ 1/2（小規模 2/3）", "公募回制；第 8 回 8/18 公募开始、9 月中旬受付、10 月中旬締切预定", "无"],
              ["東京都中小企業振興公社 各类助成金", "产品开发、贩路开拓、展会出展等", "按事业不同：300 万〜2,000 万円 / 1/2〜2/3", "各事业独立公募，多数明确写「個人事業主可」", "无"],
              ["キャリアアップ助成金（正社員化コース）", "把有期/兼职员工转为正社员", "每人 20 万〜80 万円（有期→正規·重点支援对象 80 万）", "通年受付；转正前需提交キャリアアップ計画（届出のみ）", "有：需雇用保险被保险者"],
              ["人材開発支援助成金", "给员工做培训", "经费助成 45%〜75% + 赁金助成 800〜1,000 円/小时", "训练开始前 1〜6 个月提计划届", "有"],
            ],
          },
          { type: "note", text: "「補助金」（経産省系）是竞争採択制——符合条件不等于一定获批；「助成金」（厚労省系）是要件满足原则支给。两者性质不同，规划时不要混。详见《补助金 vs 助成金》对比页。" },
          { type: "links", items: [{ label: "补助金与助成金的区别", href: "/compare" }, { label: "看最新公募截止", href: "/schedule" }] },
        ],
      },
      {
        id: "cannot",
        h2: "这些情况不能申请或很难通过",
        blocks: [
          { type: "ul", items: [
            "没有提交開業届、或没有確定申告记录——审查时无法证明事业实体与收入。",
            "在留资格不允许经营活动（如留学、家族滞在无资格外活动许可）——资格问题先解决，再谈补助金。",
            "已经签了合同、付了款再来申请——绝大多数補助金只补助「交付決定后」发生的费用，先买后报基本无效。",
            "申请目的与制度目的不匹配——例如想用持続化補助金买车、付房租，这些多为不可经费。",
            "税金滞纳、社会保险未加入（有员工时）——多数制度在要件或加减分中体现。",
            "同一费用重复申请多个国家补助金——禁止重复受领。",
          ] },
        ],
      },
      {
        id: "prepare",
        h2: "从开业到申请：准备清单",
        blocks: [
          { type: "ol", items: [
            "確認在留资格允许经营（经营管理、永住、定住、日本人配偶者等，或已获资格外活动许可）。",
            "向税务署提交開業届（個人事業の開業・廃業等届出書），建议同时提交青色申告承認申請書。",
            "按期完成確定申告并保留申告書控（含受付印或 e-Tax 受信通知）。",
            "取得 GビズID プライムアカウント（在线申请、需印鉴登录证明或マイナンバーカード，审核约 1〜2 周）——jGrants 与多数电子申请必需。",
            "整理事业计划：现在做什么、想做什么、投多少钱、预期效果（销售额/人效）——这是审查核心。",
            "持続化補助金还需向所在地商工会/商工会議所申请「事業支援計画書（様式4）」，有独立截止日（第 20 回为 12-04）。",
            "AI導入補助金需先选定登记在名录内的 IT 導入支援事業者与 IT 工具，由其共同申请。",
          ] },
          { type: "note", text: "个人事业主最容易卡在两处：GビズID 没提前办（临近截止申请不下来）和様式4 错过商工会截止。两项都请预留 3〜4 周。" },
        ],
      },
      {
        id: "cases",
        h2: "两个典型场景",
        blocks: [
          { type: "h3", text: "场景 A：一人经营的网店 / 自媒体工作室" },
          { type: "p", text: "想做官网+预约系统+广告投放。路线：持続化補助金（网站制作、广告费属于可经费范畴，通常枠上限 50 万円·2/3）；若系统属登记 IT 工具，可评估 AI導入補助金（1/2 以内）。两者不能对同一费用重复。" },
          { type: "h3", text: "场景 B：夫妻经营的小餐馆（雇 2 名兼职）" },
          { type: "p", text: "想上自动点餐/收银机、并把一名兼职转正。路线：设备走省力化補助金一般型（5 人以下档 750 万円上限，1/2，小規模 2/3；需在カタログ/一般型规则内）或 AI導入補助金；转正走キャリアアップ助成金正社員化コース（有期→正規·重点支援对象每人 80 万円）。注意助成金需在转正前提交計画届。" },
        ],
      },
      {
        id: "how-we-help",
        h2: "志成能为个人事业主做什么",
        blocks: [
          { type: "ul", items: [
            "中文免费诊断：根据在留资格、行业、员工数、想做的事，给出「能报 / 不建议报 / 需先补哪一步」。",
            "制度匹配与时间倒推：对照公募日历，告诉你现在该准备什么、几周内要办完 GビズID/様式4。",
            "材料与事业计划支持：行政书士负责补助金书类制作；雇用类助成金手续由社会保险劳务士依法办理；税理士核对财务数据。",
            "采択后的实绩报告与入金跟进——很多人不知道获批只是开始，实绩报告不合规拿不到钱。",
          ] },
          { type: "links", items: [{ label: "查看服务流程与费用", href: "/service" }, { label: "3 分钟免费资格诊断", href: "/contact" }] },
        ],
      },
    ],
    faq: [
      { q: "個人事業主和法人在补助金申请上有区别吗？", a: "在资格上大多数制度一视同仁，都属「中小企業者・小規模事業者」。区别主要在证明材料：法人提交決算書与登記簿，個人事業主提交確定申告書与開業届。部分制度（如省力化一般型 21 人以上的行动计划公表要件）与规模挂钩，与法人形态无关。" },
      { q: "持有经营管理签证的个人事业主能申请吗？", a: "在留资格允许经营活动即可申请，经营管理签证本身不构成障碍。需要注意的是补助金不会直接改善签证更新条件，但合规经营、按期申告本身对更新有利。签证相关问题请咨询行政书士，本页不构成法律意见。" },
      { q: "没有员工的个人事业主能申请キャリアアップ助成金吗？", a: "不能。该助成金以「雇用保险被保险者」的处遇改善为对象，没有雇用关系无从谈起。若计划雇人，建议先合规加入劳动·社会保险，再在转正前提交キャリアアップ計画届。" },
      { q: "持続化補助金的 50 万円上限太低，有没有更高的？", a: "通常枠上限 50 万円，但赁金引上げ特例、卒業枠、後継者支援、創業型等特例最高可到 200 万円，另有インボイス特例 +50 万円。适用哪一档取决于是否满足特例要件（如员工涨薪、创业未满 3 年等），以第 20 回公募要領为准。" },
      { q: "先买了设备/先签了合同，还能补申请吗？", a: "原则上不能。持続化、省力化、AI導入均只补助「交付決定」之后发生的契约与支出（部分制度允许「事前着手承认」，需另行申请）。这是个人事业主被拒或被要求返还最常见的原因，务必先申请再采购。" },
      { q: "从准备到拿到钱大概多久？", a: "以持続化補助金为例：公募申请→約 2〜3 个月採択发表→交付決定→实施事业（数月）→实绩报告→审核→入金，整体 8〜12 个月是常见节奏。AI導入補助金流程更短，通常 6〜9 个月。补助金是「先花后补」，需要自筹周转资金。" },
      { q: "找顾问代办要多少钱？个人事业主也值得吗？", a: "行业常见为成功报酬制（获批额的一定比例）加或不加着手金。金额较小的持続化補助金是否委托，取决于你的时间成本与对制度熟悉度；志成提供免费诊断，先判断能不能报、值不值得报，再谈是否委托。" },
      { q: "被拒了还能再申请吗？", a: "可以。持続化、省力化、AI導入都是多回公募，不採択可在下一回改善计划后再报，无次数惩罚。但要分析原因：是要件不满足（先补要件）还是计划书评分低（改计划）。" },
    ],
    sources: [
      { label: "小規模事業者持続化補助金〈一般型〉公式（第 20 回公募要領·受付日程）", url: SRC.jizokuka },
      { label: "デジタル化・AI導入補助金2026 公式（中小機構）", url: SRC.itshien },
      { label: "中小企業省力化投資補助事業（一般型）公式（第 8 回公募日程）", url: SRC.seiryoka },
      { label: "キャリアアップ助成金（厚生労働省）", url: SRC.career },
      { label: "人材開発支援助成金（厚生労働省）", url: SRC.jinzai },
      { label: "東京都中小企業振興公社 助成金一覧", url: SRC.kosha },
      { label: "GビズID（デジタル庁）", url: SRC.gbiz },
    ],
    verifiedDate: VERIFIED,
    related: RELATED.zh,
    ctaTitle1: "不确定自己能不能报？",
    ctaTitle2: "3 分钟中文免费诊断",
    ctaDesc: "告诉我们在留资格、行业、员工数、想做的事，工作日 1 个营业日内回复「能报什么·先补哪一步」。不获批不收费。",
    breadcrumbParent: { label: "谁能申请", href: "/subsidies" },
    ui: UI.zh,
  },
  en: {
    path: "/for/sole-proprietor",
    metaTitle: "Which Japanese Subsidies Can a Sole Proprietor Apply For? 2026 List & Conditions",
    metaDesc: "Sole proprietors (kojin jigyonushi) in Japan can apply for the Small Business Sustainability Subsidy, Digitalization & AI Adoption Subsidy 2026, Labor-Saving Investment Subsidy and Tokyo grants; Career-Up Grant once you employ staff. Conditions, amounts, checklist and Chinese-language support.",
    keywords: ["sole proprietor subsidy Japan", "kojin jigyonushi hojokin", "Japan freelancer grant", "small business subsidy Japan foreigner"],
    heroEyebrow: "For sole proprietors",
    heroTitle1: "Japanese subsidies & grants",
    heroTitle2: "sole proprietors can actually use (2026)",
    heroDesc: "No company, no employees — there are still programs you qualify for. This page covers only the ones that matter for kojin jigyonushi: who qualifies, how much, when, and what to prepare.",
    summary: "A sole proprietor in Japan can apply for four main programs: ① Small Business Sustainability Subsidy (standard cap ¥500,000, 2/3 rate, up to ¥2M with special tracks); ② Digitalization & AI Adoption Subsidy 2026 (¥50,000–¥4.5M, up to 1/2); ③ Labor-Saving Investment Subsidy general type (cap ¥7.5M for ≤5 staff, 1/2 rate, 2/3 for small businesses); ④ Tokyo Metropolitan grants. After hiring staff, the Career-Up Grant pays up to ¥800,000 per regularized employee. Prerequisites: a filed business-opening notice, tax-return history and a GビズID.",
    quickFacts: [
      { label: "Most used", value: "Sustainability Subsidy", sub: "Cap ¥500k · 2/3; 20th round 2026-11-05 to 12-15" },
      { label: "Software / systems", value: "AI Adoption up to ¥4.5M", sub: "Rate up to 1/2; joint application with a registered IT vendor" },
      { label: "Equipment", value: "Labor-Saving ¥7.5M", sub: "≤5 staff tier; 1/2 (2/3 small business)" },
      { label: "After hiring", value: "Up to ¥800k / person", sub: "Career-Up Grant regularization course, year-round" },
    ],
    sections: [
      { id: "can-i-apply", h2: "Three questions we hear most", blocks: [
        { type: "h3", text: "① Can I apply without a company?" },
        { type: "p", text: "Yes. Nearly every program for 'SMEs and small businesses' explicitly includes sole proprietors. Eligibility depends on having a registered business (opening notice), filing tax returns, and staying within the industry/headcount limits — not on incorporation." },
        { type: "h3", text: "② I work alone. Can I get employment grants?" },
        { type: "p", text: "MHLW grants (Career-Up, Human Resource Development) require employees covered by employment insurance, so a one-person business cannot use them. METI subsidies (Sustainability, AI Adoption, Labor-Saving) have no employee requirement." },
        { type: "h3", text: "③ How long after opening?" },
        { type: "p", text: "The Sustainability Subsidy requires an opened business and, normally, a tax return (first-year businesses may substitute the opening notice per the round's guidelines). AI Adoption and Labor-Saving have no hard minimum, but at least one filed return strengthens the review." },
      ] },
      { id: "list", h2: "Programs open to sole proprietors in 2026", blocks: [
        { type: "table", caption: "Per official guidelines, verified 2026-09-03", head: ["Program", "Use", "Cap / rate", "Window", "Staff required?"], rows: [
          ["Small Business Sustainability Subsidy (general, standard)", "Marketing, website, renovation, trade shows", "¥500k / 2/3 (special tracks up to ¥2M; invoice special +¥500k)", "Round-based; 20th round 2026-11-05 to 12-15 17:00, Form 4 by 12-04", "No (≤5 regular staff in retail/services)"],
          ["Digitalization & AI Adoption Subsidy 2026", "Accounting, booking, POS, AI tools", "¥50k–¥4.5M / up to 1/2 (2/3 with wage condition)", "Monthly deadlines; joint application with registered IT vendor", "No"],
          ["Labor-Saving Investment Subsidy (general)", "Automation equipment, labor-saving systems", "¥7.5M (≤5 staff; ¥10M with wage-raise special) / 1/2 (2/3 small)", "Round 8: opens 8/18, intake mid-Sep, deadline mid-Oct (planned)", "No"],
          ["Tokyo SME Support Center grants", "Product development, market expansion, exhibitions", "¥3M–¥20M / 1/2–2/3 by program", "Separate calls; most explicitly list sole proprietors", "No"],
          ["Career-Up Grant (regularization)", "Convert fixed-term/part-time staff to regular", "¥200k–¥800k per person", "Year-round; plan notification before conversion", "Yes"],
          ["Human Resource Development Grant", "Staff training", "45–75% of costs + ¥800–1,000/hour wage support", "Plan filed 1–6 months before training", "Yes"],
        ] },
        { type: "note", text: "METI 'subsidies' are competitive — meeting conditions does not guarantee adoption. MHLW 'grants' are paid when requirements are met. Plan accordingly." },
        { type: "links", items: [{ label: "Subsidy vs. grant", href: "/compare" }, { label: "Deadlines calendar", href: "/schedule" }] },
      ] },
      { id: "cannot", h2: "When you cannot apply (or will likely fail)", blocks: [
        { type: "ul", items: [
          "No opening notice or tax-return history.",
          "Residence status that does not permit business activity.",
          "Contract signed or payment made before the grant decision — most subsidies only cover costs incurred after 交付決定.",
          "Purpose mismatch (e.g., vehicles or rent under the Sustainability Subsidy are usually ineligible).",
          "Tax arrears or, with employees, no social-insurance enrollment.",
          "Double-claiming the same cost under two national subsidies.",
        ] },
      ] },
      { id: "prepare", h2: "Checklist: from opening to application", blocks: [
        { type: "ol", items: [
          "Confirm your residence status permits business activity.",
          "File the business-opening notice (and ideally the blue-return approval) with the tax office.",
          "File tax returns on time and keep stamped copies / e-Tax receipts.",
          "Obtain a GビズID Prime account (1–2 weeks) — required for jGrants and most e-applications.",
          "Draft the business plan: current state, investment, expected sales/productivity effect.",
          "Sustainability Subsidy: request Form 4 from your local Chamber of Commerce (separate deadline, 12-04 for round 20).",
          "AI Adoption: choose a registered IT vendor and tool; they co-apply.",
        ] },
        { type: "note", text: "The two most common blockers: GビズID applied too late, and missing the Chamber's Form 4 deadline. Allow 3–4 weeks for each." },
      ] },
      { id: "cases", h2: "Two typical scenarios", blocks: [
        { type: "h3", text: "A: One-person online shop / studio" },
        { type: "p", text: "Website, booking system and ads → Sustainability Subsidy (cap ¥500k, 2/3). If the system is a registered IT tool, evaluate the AI Adoption Subsidy instead — never both for the same cost." },
        { type: "h3", text: "B: Family restaurant with two part-timers" },
        { type: "p", text: "Self-ordering/POS → Labor-Saving (≤5 staff: ¥7.5M cap) or AI Adoption; converting one part-timer → Career-Up Grant (¥800k for fixed-term → regular, priority target). File the Career-Up plan before conversion." },
      ] },
      { id: "how-we-help", h2: "How Shisei helps sole proprietors", blocks: [
        { type: "ul", items: [
          "Free diagnosis in Chinese: what you can apply for, what to fix first.",
          "Timeline planning against the official calendar (GビズID, Form 4, deadlines).",
          "Documents: Gyoseishoshi prepares subsidy documents; Sharoshi handles employment-grant procedures; Zeirishi verifies financials.",
          "Post-adoption reporting until funds arrive.",
        ] },
        { type: "links", items: [{ label: "Process & fees", href: "/service" }, { label: "3-minute free diagnosis", href: "/contact" }] },
      ] },
    ],
    faq: [
      { q: "Do sole proprietors and companies differ in eligibility?", a: "Mostly no — both count as SMEs/small businesses. The difference is documentation: companies submit financial statements and registry; sole proprietors submit tax returns and the opening notice." },
      { q: "Can a Business Manager visa holder apply?", a: "Yes, if the status permits the business activity. Subsidies do not directly affect visa renewal; consult a Gyoseishoshi for immigration matters." },
      { q: "Can I get the Career-Up Grant with no employees?", a: "No. It targets employees covered by employment insurance. Enroll staff properly first, then file the plan before conversion." },
      { q: "Is ¥500k the maximum for the Sustainability Subsidy?", a: "Standard track, yes. Special tracks (wage increase, startup, successor) go up to ¥2M, plus a ¥500k invoice special, subject to the round's guidelines." },
      { q: "I already bought the equipment. Can I apply retroactively?", a: "Generally no — only costs after the grant decision are eligible. This is the most common cause of rejection or repayment." },
      { q: "How long until the money arrives?", a: "Sustainability Subsidy: typically 8–12 months end-to-end; AI Adoption: 6–9 months. Subsidies reimburse after you pay, so plan cash flow." },
      { q: "Is hiring a consultant worth it for small amounts?", a: "Depends on your time and familiarity. Our diagnosis is free — we first tell you whether it is worth applying at all." },
      { q: "Can I reapply after rejection?", a: "Yes. All three METI subsidies run multiple rounds with no penalty; fix the requirement gap or improve the plan first." },
    ],
    sources: [
      { label: "Small Business Sustainability Subsidy (official)", url: SRC.jizokuka },
      { label: "Digitalization & AI Adoption Subsidy 2026 (SMRJ)", url: SRC.itshien },
      { label: "Labor-Saving Investment Subsidy (official)", url: SRC.seiryoka },
      { label: "Career-Up Grant (MHLW)", url: SRC.career },
      { label: "Human Resource Development Grant (MHLW)", url: SRC.jinzai },
      { label: "Tokyo SME Support Center grants", url: SRC.kosha },
      { label: "GビズID", url: SRC.gbiz },
    ],
    verifiedDate: VERIFIED,
    related: RELATED.en,
    ctaTitle1: "Not sure you qualify? ",
    ctaTitle2: "Free 3-minute diagnosis",
    ctaDesc: "Tell us your status, industry, headcount and goal. We reply within one business day with what you can apply for. No approval, no fee.",
    breadcrumbParent: { label: "Subsidies", href: "/subsidies" },
    ui: UI.en,
  },
  ja: {
    path: "/for/sole-proprietor",
    metaTitle: "個人事業主が申請できる補助金・助成金一覧（2026）｜要件・金額・準備チェックリスト",
    metaDesc: "個人事業主でも申請できる補助金・助成金を整理。小規模事業者持続化補助金、デジタル化・AI導入補助金2026、中小企業省力化投資補助金（一般型）、東京都の助成金、雇用後のキャリアアップ助成金。要件・上限額・受付期間・準備事項を中国語対応でサポート。",
    keywords: ["個人事業主 補助金", "個人事業主 助成金", "持続化補助金 個人事業主", "外国人 個人事業主 補助金", "中国語対応 補助金"],
    heroEyebrow: "個人事業主向け",
    heroTitle1: "個人事業主でも使える",
    heroTitle2: "補助金・助成金一覧（2026年版）",
    heroDesc: "法人でなくても、従業員がいなくても、対象となる制度はあります。本ページでは個人事業主が実際に使える制度に絞り、対象・金額・時期・事前準備を整理します。",
    summary: "日本で個人事業主として事業を営む方が申請できる主な制度は4系統です。①小規模事業者持続化補助金（通常枠上限50万円・補助率2/3、特例で最大200万円）、②デジタル化・AI導入補助金2026（通常枠5万〜450万円・補助率1/2以内）、③中小企業省力化投資補助金一般型（従業員5人以下は上限750万円・補助率1/2、小規模事業者2/3）、④東京都中小企業振興公社などの地方助成金。従業員を雇用した後はキャリアアップ助成金（正社員化コース：1人最大80万円）も対象です。前提として開業届の提出、確定申告の実績、GビズIDの取得が必要です。",
    quickFacts: [
      { label: "最も使われる制度", value: "持続化補助金", sub: "通常枠上限50万円・2/3；第20回受付 2026-11-05〜12-15" },
      { label: "ITツール・システム", value: "AI導入補助金 最大450万円", sub: "補助率1/2以内；IT導入支援事業者との共同申請" },
      { label: "設備投資", value: "省力化（一般型）750万円", sub: "5人以下の区分；1/2（小規模2/3）" },
      { label: "雇用後", value: "正社員化 1人最大80万円", sub: "キャリアアップ助成金・通年受付" },
    ],
    sections: [
      { id: "can-i-apply", h2: "よくある3つの質問に先にお答えします", blocks: [
        { type: "h3", text: "① 法人でなくても申請できますか？" },
        { type: "p", text: "できます。「中小企業者・小規模事業者」向けの制度は、ほぼすべて個人事業主を対象に含みます。判断基準は法人格ではなく、開業届の有無、確定申告の実績、業種と常時使用従業員数です。" },
        { type: "h3", text: "② 一人で経営していますが助成金は使えますか？" },
        { type: "p", text: "厚生労働省系の助成金（キャリアアップ・人材開発支援など）は雇用保険被保険者の存在が前提のため、一人経営では原則対象外です。経済産業省系の補助金（持続化・AI導入・省力化）には従業員要件がありません。" },
        { type: "h3", text: "③ 開業後どのくらいで申請できますか？" },
        { type: "p", text: "持続化補助金は申請時点で開業済みであり、原則確定申告書が必要（創業1年未満は開業届で代替可、当該回の公募要領に準じます）。AI導入・省力化には年数要件はありませんが、1期以上の申告実績があると審査上有利です。" },
      ] },
      { id: "list", h2: "2026年 個人事業主が申請できる制度一覧", blocks: [
        { type: "table", caption: "金額・補助率は各制度の公募要領に準じます（2026-09-03確認）", head: ["制度", "使途", "上限／補助率", "受付", "従業員要件"], rows: [
          ["小規模事業者持続化補助金〈一般型 通常枠〉", "販路開拓：Web・広告・店舗改装・展示会", "50万円／2/3（賃金引上げ等特例で最大200万円、インボイス特例+50万円）", "公募回制；第20回 2026-11-05〜12-15 17:00、様式4発行締切 12-04", "なし（商業・サービス業は常時従業員5人以下）"],
          ["デジタル化・AI導入補助金2026", "会計・予約・POS・AIツール等", "通常枠5万〜450万円／1/2以内（最低賃金要件で2/3）", "月次締切；登録IT導入支援事業者と共同申請", "なし"],
          ["中小企業省力化投資補助事業（一般型）", "自動化設備・省人化システム", "5人以下750万円（大幅賃上げ特例1,000万）／1/2（小規模2/3）", "公募回制；第8回 8/18公募開始・9月中旬受付・10月中旬締切予定", "なし"],
          ["東京都中小企業振興公社 各助成金", "製品開発・販路開拓・展示会出展", "事業により300万〜2,000万円／1/2〜2/3", "事業ごとに公募；多くが「個人事業主可」", "なし"],
          ["キャリアアップ助成金（正社員化コース）", "有期・パートの正社員転換", "1人20万〜80万円", "通年；転換前にキャリアアップ計画の届出", "あり"],
          ["人材開発支援助成金", "従業員の訓練", "経費助成45〜75%＋賃金助成800〜1,000円/時", "訓練開始1〜6か月前に計画届", "あり"],
        ] },
        { type: "note", text: "経産省系「補助金」は競争的な採択審査、厚労省系「助成金」は要件を満たせば原則支給。性質が異なるため計画時に混同しないようご注意ください。" },
        { type: "links", items: [{ label: "補助金と助成金の違い", href: "/compare" }, { label: "最新の公募締切", href: "/schedule" }] },
      ] },
      { id: "cannot", h2: "申請できない・通りにくいケース", blocks: [
        { type: "ul", items: [
          "開業届未提出、または確定申告の実績がない。",
          "在留資格が事業活動を許可していない。",
          "契約・支払いを先に済ませている——多くの補助金は交付決定後の経費のみ対象。",
          "使途が制度目的と合わない（車両・家賃など）。",
          "税金の滞納、従業員がいるのに社会保険未加入。",
          "同一経費を複数の国の補助金に重複申請。",
        ] },
      ] },
      { id: "prepare", h2: "開業から申請までの準備チェックリスト", blocks: [
        { type: "ol", items: [
          "在留資格が事業活動を許可しているか確認。",
          "税務署へ開業届（併せて青色申告承認申請書）を提出。",
          "期限内に確定申告し、控え（受付印またはe-Tax受信通知）を保管。",
          "GビズIDプライムを取得（審査1〜2週間）。jGrants等の電子申請に必須。",
          "事業計画の整理：現状・投資内容・期待効果（売上・生産性）。",
          "持続化補助金は商工会・商工会議所へ「事業支援計画書（様式4）」を依頼（第20回は12-04締切）。",
          "AI導入補助金は登録IT導入支援事業者とITツールを選定し共同申請。",
        ] },
        { type: "note", text: "つまずきやすいのは「GビズIDの取得遅れ」と「様式4の締切失念」。それぞれ3〜4週間の余裕を。" },
      ] },
      { id: "cases", h2: "典型的な2つのケース", blocks: [
        { type: "h3", text: "A：一人で運営するネットショップ・スタジオ" },
        { type: "p", text: "Webサイト・予約システム・広告 → 持続化補助金（上限50万円・2/3）。システムが登録ITツールならAI導入補助金（1/2以内）を検討。同一経費の重複は不可。" },
        { type: "h3", text: "B：パート2名を雇う家族経営の飲食店" },
        { type: "p", text: "セルフオーダー・POS → 省力化補助金一般型（5人以下750万円上限）またはAI導入補助金。パート1名の正社員化 → キャリアアップ助成金（有期→正規・重点支援対象 80万円）。転換前に計画届が必要。" },
      ] },
      { id: "how-we-help", h2: "志成コンサルのサポート", blocks: [
        { type: "ul", items: [
          "中国語での無料診断：申請可能な制度と、先に整えるべき事項をご提示。",
          "公募カレンダーに基づく逆算スケジュール（GビズID・様式4・締切）。",
          "書類作成：補助金書類は行政書士、雇用関係助成金の手続きは社会保険労務士、財務確認は税理士が担当。",
          "採択後の実績報告から入金までフォロー。",
        ] },
        { type: "links", items: [{ label: "サービスの流れ・費用", href: "/service" }, { label: "3分で無料診断", href: "/contact" }] },
      ] },
    ],
    faq: [
      { q: "個人事業主と法人で申請要件は違いますか？", a: "多くの制度で同じ「中小企業者・小規模事業者」として扱われます。違いは証明書類で、法人は決算書・登記簿、個人事業主は確定申告書・開業届を提出します。" },
      { q: "経営・管理ビザの個人事業主でも申請できますか？", a: "在留資格が事業活動を許可していれば申請可能です。補助金がビザ更新要件を直接変えるものではありません。在留資格については行政書士へご相談ください。" },
      { q: "従業員がいない場合、キャリアアップ助成金は使えますか？", a: "使えません。雇用保険被保険者の処遇改善が対象です。雇用する場合は労働・社会保険に適正加入のうえ、転換前に計画届を提出してください。" },
      { q: "持続化補助金の上限は50万円だけですか？", a: "通常枠は50万円ですが、賃金引上げ特例・創業型・後継者支援などで最大200万円、インボイス特例で+50万円となります。適用は第20回公募要領に準じます。" },
      { q: "先に設備を購入しました。後から申請できますか？", a: "原則できません。交付決定後の契約・支出のみが対象です（事前着手承認制度がある場合を除く）。不採択・返還の最多原因です。" },
      { q: "申請から入金までどのくらいかかりますか？", a: "持続化補助金で8〜12か月、AI導入補助金で6〜9か月が一般的です。補助金は後払いのため、資金繰りの計画が必要です。" },
      { q: "少額でも専門家に依頼する価値はありますか？", a: "ご自身の時間コストと制度理解度によります。当社の診断は無料で、まず「申請すべきか」をお伝えします。" },
      { q: "不採択後に再申請できますか？", a: "できます。3制度とも複数回公募があり、再申請にペナルティはありません。要件不足か計画内容かを分析して改善してください。" },
    ],
    sources: [
      { label: "小規模事業者持続化補助金〈一般型〉公式", url: SRC.jizokuka },
      { label: "デジタル化・AI導入補助金2026（中小機構）", url: SRC.itshien },
      { label: "中小企業省力化投資補助事業（一般型）公式", url: SRC.seiryoka },
      { label: "キャリアアップ助成金（厚生労働省）", url: SRC.career },
      { label: "人材開発支援助成金（厚生労働省）", url: SRC.jinzai },
      { label: "東京都中小企業振興公社 助成金一覧", url: SRC.kosha },
      { label: "GビズID", url: SRC.gbiz },
    ],
    verifiedDate: VERIFIED,
    related: RELATED.ja,
    ctaTitle1: "対象かどうか分からない方へ ",
    ctaTitle2: "3分で無料診断",
    ctaDesc: "在留資格・業種・従業員数・やりたいことをお知らせください。1営業日以内に「申請できる制度・先に整えること」をご回答します。不採択なら費用はいただきません。",
    breadcrumbParent: { label: "補助金の種類", href: "/subsidies" },
    ui: UI.ja,
  },
};
